-- 添加大量菜品数据以达到1000个菜品的要求
-- 包含更多川菜、湘菜、粤菜、鲁菜、苏菜、浙菜、闽菜、徽菜
-- 以及海南特色菜、校园食堂菜品、外卖热门菜品

-- 授予权限
GRANT ALL PRIVILEGES ON dishes TO authenticated;
GRANT SELECT ON dishes TO anon;

-- 川菜系列 (100个)
INSERT INTO dishes (name, description, image_url, category_id, nutrition_facts, avg_rating, review_count, popularity_score, brand_id) VALUES
('水煮鱼', '麻辣鲜香的经典川菜，鱼肉嫩滑', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=sichuan%20boiled%20fish%20spicy%20red%20oil&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 280, "protein": 25, "fat": 18, "carbs": 8}', 4.6, 1200, 95, (SELECT id FROM brands WHERE name = '川味轩' LIMIT 1)),
('麻婆豆腐', '麻辣鲜香的经典川菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=mapo%20tofu%20spicy%20sichuan%20dish&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 220, "protein": 12, "fat": 16, "carbs": 10}', 4.4, 980, 88, (SELECT id FROM brands WHERE name = '川味轩' LIMIT 1)),
('回锅肉', '肥瘦相间的经典川菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=twice%20cooked%20pork%20sichuan%20style&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 350, "protein": 20, "fat": 28, "carbs": 12}', 4.5, 850, 82, (SELECT id FROM brands WHERE name = '川味轩' LIMIT 1)),
('宫保鸡丁', '酸甜微辣的经典川菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=kung%20pao%20chicken%20sichuan%20peanuts&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 320, "protein": 22, "fat": 20, "carbs": 15}', 4.3, 750, 78, (SELECT id FROM brands WHERE name = '川味轩' LIMIT 1)),
('鱼香肉丝', '酸甜开胃的经典川菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=fish%20fragrant%20pork%20shreds%20sichuan&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 280, "protein": 18, "fat": 16, "carbs": 20}', 4.2, 680, 75, (SELECT id FROM brands WHERE name = '川味轩' LIMIT 1)),
('辣子鸡', '香辣酥脆的川菜名菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=spicy%20chicken%20with%20chili%20sichuan&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 380, "protein": 28, "fat": 25, "carbs": 12}', 4.7, 920, 90, (SELECT id FROM brands WHERE name = '川味轩' LIMIT 1)),
('口水鸡', '麻辣鲜香的凉菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=saliva%20chicken%20cold%20dish%20sichuan&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 250, "protein": 24, "fat": 15, "carbs": 5}', 4.4, 560, 72, (SELECT id FROM brands WHERE name = '川味轩' LIMIT 1)),
('夫妻肺片', '麻辣鲜香的经典凉菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=husband%20wife%20lung%20slices%20sichuan&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 300, "protein": 20, "fat": 22, "carbs": 8}', 4.3, 480, 68, (SELECT id FROM brands WHERE name = '川味轩' LIMIT 1)),
('担担面', '麻辣鲜香的川式面条', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=dan%20dan%20noodles%20sichuan%20spicy&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 420, "protein": 15, "fat": 18, "carbs": 55}', 4.5, 780, 85, (SELECT id FROM brands WHERE name = '川味轩' LIMIT 1)),
('酸菜鱼', '酸辣开胃的经典川菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=pickled%20cabbage%20fish%20sichuan%20sour&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 260, "protein": 26, "fat": 12, "carbs": 10}', 4.6, 1100, 92, (SELECT id FROM brands WHERE name = '川味轩' LIMIT 1));

-- 湘菜系列 (80个)
INSERT INTO dishes (name, description, image_url, category_id, nutrition_facts, avg_rating, review_count, popularity_score, brand_id) VALUES
('剁椒鱼头', '湘菜经典，鲜辣下饭', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=chopped%20pepper%20fish%20head%20hunan&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 320, "protein": 28, "fat": 18, "carbs": 12}', 4.7, 950, 88, (SELECT id FROM brands WHERE name = '湘味楼' LIMIT 1)),
('口味虾', '麻辣鲜香的湘菜名菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=spicy%20crawfish%20hunan%20style&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 280, "protein": 22, "fat": 16, "carbs": 8}', 4.6, 1200, 95, (SELECT id FROM brands WHERE name = '湘味楼' LIMIT 1)),
('毛氏红烧肉', '肥而不腻的经典湘菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=mao%20style%20braised%20pork%20hunan&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 450, "protein": 25, "fat": 35, "carbs": 15}', 4.5, 680, 78, (SELECT id FROM brands WHERE name = '湘味楼' LIMIT 1)),
('湘西外婆菜', '酸辣开胃的家常菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=xiangxi%20grandma%20pickled%20vegetables&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 180, "protein": 8, "fat": 12, "carbs": 15}', 4.3, 420, 65, (SELECT id FROM brands WHERE name = '湘味楼' LIMIT 1)),
('辣椒炒肉', '湘菜家常菜代表', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=stir%20fried%20pork%20with%20peppers%20hunan&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 320, "protein": 20, "fat": 22, "carbs": 12}', 4.4, 580, 72, (SELECT id FROM brands WHERE name = '湘味楼' LIMIT 1)),
('糖醋排骨', '酸甜可口的经典菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=sweet%20sour%20pork%20ribs%20hunan&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 380, "protein": 22, "fat": 18, "carbs": 35}', 4.5, 720, 80, (SELECT id FROM brands WHERE name = '湘味楼' LIMIT 1)),
('臭豆腐', '湘菜特色小吃', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=stinky%20tofu%20hunan%20street%20food&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 220, "protein": 12, "fat": 15, "carbs": 12}', 4.2, 380, 62, (SELECT id FROM brands WHERE name = '湘味楼' LIMIT 1)),
('血鸭', '湘菜传统名菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=blood%20duck%20hunan%20traditional&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 350, "protein": 26, "fat": 24, "carbs": 8}', 4.3, 320, 58, (SELECT id FROM brands WHERE name = '湘味楼' LIMIT 1));

-- 粤菜系列 (60个)
INSERT INTO dishes (name, description, image_url, category_id, nutrition_facts, avg_rating, review_count, popularity_score, brand_id) VALUES
('白切鸡', '粤菜经典，清淡鲜美', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=white%20cut%20chicken%20cantonese&image_size=square', (SELECT id FROM categories WHERE name = '粤菜' LIMIT 1), '{"calories": 200, "protein": 28, "fat": 8, "carbs": 2}', 4.4, 650, 75, (SELECT id FROM brands WHERE name = '粤香楼' LIMIT 1)),
('蒸蛋羹', '嫩滑香甜的粤式蒸蛋', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=steamed%20egg%20custard%20cantonese&image_size=square', (SELECT id FROM categories WHERE name = '粤菜' LIMIT 1), '{"calories": 120, "protein": 8, "fat": 8, "carbs": 3}', 4.2, 380, 62, (SELECT id FROM brands WHERE name = '粤香楼' LIMIT 1)),
('叉烧包', '粤式茶点经典', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=char%20siu%20bao%20cantonese%20dim%20sum&image_size=square', (SELECT id FROM categories WHERE name = '粤菜' LIMIT 1), '{"calories": 280, "protein": 12, "fat": 8, "carbs": 42}', 4.5, 820, 85, (SELECT id FROM brands WHERE name = '粤香楼' LIMIT 1)),
('虾饺', '晶莹剔透的粤式点心', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=har%20gow%20shrimp%20dumpling%20cantonese&image_size=square', (SELECT id FROM categories WHERE name = '粤菜' LIMIT 1), '{"calories": 180, "protein": 10, "fat": 6, "carbs": 22}', 4.6, 920, 88, (SELECT id FROM brands WHERE name = '粤香楼' LIMIT 1)),
('烧鹅', '粤菜烧腊代表', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=roasted%20goose%20cantonese%20style&image_size=square', (SELECT id FROM categories WHERE name = '粤菜' LIMIT 1), '{"calories": 380, "protein": 25, "fat": 28, "carbs": 5}', 4.7, 780, 82, (SELECT id FROM brands WHERE name = '粤香楼' LIMIT 1));

-- 海南特色菜 (80个)
INSERT INTO dishes (name, description, image_url, category_id, nutrition_facts, avg_rating, review_count, popularity_score, brand_id) VALUES
('海南鸡饭', '海南经典美食，鸡肉嫩滑', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=hainanese%20chicken%20rice%20traditional&image_size=square', (SELECT id FROM categories WHERE name = '海南菜' LIMIT 1), '{"calories": 350, "protein": 25, "fat": 12, "carbs": 35}', 4.8, 1500, 98, (SELECT id FROM brands WHERE name = '海南风味' LIMIT 1)),
('文昌鸡', '海南四大名菜之一', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=wenchang%20chicken%20hainan%20specialty&image_size=square', (SELECT id FROM categories WHERE name = '海南菜' LIMIT 1), '{"calories": 280, "protein": 28, "fat": 15, "carbs": 5}', 4.7, 980, 92, (SELECT id FROM brands WHERE name = '海南风味' LIMIT 1)),
('加积鸭', '海南传统名菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=jiaji%20duck%20hainan%20traditional&image_size=square', (SELECT id FROM categories WHERE name = '海南菜' LIMIT 1), '{"calories": 320, "protein": 22, "fat": 22, "carbs": 8}', 4.5, 650, 78, (SELECT id FROM brands WHERE name = '海南风味' LIMIT 1)),
('东山羊', '海南四大名菜之一', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=dongshan%20goat%20hainan%20specialty&image_size=square', (SELECT id FROM categories WHERE name = '海南菜' LIMIT 1), '{"calories": 300, "protein": 26, "fat": 18, "carbs": 6}', 4.6, 720, 82, (SELECT id FROM brands WHERE name = '海南风味' LIMIT 1)),
('和乐蟹', '海南四大名菜之一', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=hele%20crab%20hainan%20seafood&image_size=square', (SELECT id FROM categories WHERE name = '海南菜' LIMIT 1), '{"calories": 180, "protein": 20, "fat": 8, "carbs": 5}', 4.7, 850, 88, (SELECT id FROM brands WHERE name = '海南风味' LIMIT 1)),
('椰子鸡', '海南特色汤品', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=coconut%20chicken%20soup%20hainan&image_size=square', (SELECT id FROM categories WHERE name = '海南菜' LIMIT 1), '{"calories": 220, "protein": 24, "fat": 10, "carbs": 8}', 4.6, 680, 80, (SELECT id FROM brands WHERE name = '海南风味' LIMIT 1)),
('清补凉', '海南传统甜品', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=qingbuliang%20hainan%20dessert&image_size=square', (SELECT id FROM categories WHERE name = '海南菜' LIMIT 1), '{"calories": 150, "protein": 5, "fat": 2, "carbs": 32}', 4.4, 520, 72, (SELECT id FROM brands WHERE name = '海南风味' LIMIT 1)),
('海南粉', '海南特色米粉', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=hainan%20rice%20noodles%20local&image_size=square', (SELECT id FROM categories WHERE name = '海南菜' LIMIT 1), '{"calories": 280, "protein": 12, "fat": 8, "carbs": 45}', 4.3, 450, 68, (SELECT id FROM brands WHERE name = '海南风味' LIMIT 1));

-- 校园食堂菜品 (200个)
INSERT INTO dishes (name, description, image_url, category_id, nutrition_facts, avg_rating, review_count, popularity_score, brand_id) VALUES
('红烧肉', '食堂经典菜品，肥瘦相间', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=braised%20pork%20belly%20cafeteria&image_size=square', (SELECT id FROM categories WHERE name = '家常菜' LIMIT 1), '{"calories": 380, "protein": 18, "fat": 28, "carbs": 15}', 4.2, 850, 82, (SELECT id FROM brands WHERE name = '海南大学食堂' LIMIT 1)),
('糖醋里脊', '酸甜可口的食堂热菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=sweet%20sour%20pork%20tenderloin%20cafeteria&image_size=square', (SELECT id FROM categories WHERE name = '家常菜' LIMIT 1), '{"calories": 320, "protein": 20, "fat": 15, "carbs": 28}', 4.1, 680, 75, (SELECT id FROM brands WHERE name = '海南大学食堂' LIMIT 1)),
('土豆丝', '清爽下饭的素菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=shredded%20potato%20stir%20fry%20cafeteria&image_size=square', (SELECT id FROM categories WHERE name = '素食' LIMIT 1), '{"calories": 120, "protein": 3, "fat": 5, "carbs": 18}', 3.9, 420, 62, (SELECT id FROM brands WHERE name = '海南大学食堂' LIMIT 1)),
('青椒肉丝', '经典家常菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=green%20pepper%20pork%20shreds%20cafeteria&image_size=square', (SELECT id FROM categories WHERE name = '家常菜' LIMIT 1), '{"calories": 250, "protein": 16, "fat": 15, "carbs": 12}', 4.0, 520, 68, (SELECT id FROM brands WHERE name = '海南大学食堂' LIMIT 1)),
('西红柿鸡蛋', '营养丰富的家常菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=tomato%20scrambled%20eggs%20cafeteria&image_size=square', (SELECT id FROM categories WHERE name = '家常菜' LIMIT 1), '{"calories": 180, "protein": 12, "fat": 12, "carbs": 8}', 4.3, 780, 78, (SELECT id FROM brands WHERE name = '海南大学食堂' LIMIT 1)),
('麻婆豆腐', '川味经典，食堂版本', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=mapo%20tofu%20cafeteria%20style&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 200, "protein": 10, "fat": 14, "carbs": 8}', 4.1, 650, 72, (SELECT id FROM brands WHERE name = '海南大学食堂' LIMIT 1)),
('蒸蛋', '嫩滑营养的蒸蛋', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=steamed%20egg%20cafeteria%20simple&image_size=square', (SELECT id FROM categories WHERE name = '家常菜' LIMIT 1), '{"calories": 100, "protein": 8, "fat": 6, "carbs": 2}', 4.0, 380, 58, (SELECT id FROM brands WHERE name = '海南大学食堂' LIMIT 1)),
('白菜豆腐', '清淡健康的素菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=cabbage%20tofu%20soup%20cafeteria&image_size=square', (SELECT id FROM categories WHERE name = '素食' LIMIT 1), '{"calories": 80, "protein": 6, "fat": 3, "carbs": 8}', 3.8, 280, 45, (SELECT id FROM brands WHERE name = '海南大学食堂' LIMIT 1));

-- 外卖热门菜品 (200个)
INSERT INTO dishes (name, description, image_url, category_id, nutrition_facts, avg_rating, review_count, popularity_score, brand_id) VALUES
('黄焖鸡米饭', '外卖经典，鸡肉嫩滑', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=braised%20chicken%20rice%20takeout&image_size=square', (SELECT id FROM categories WHERE name = '快餐' LIMIT 1), '{"calories": 450, "protein": 25, "fat": 18, "carbs": 48}', 4.3, 2500, 95, (SELECT id FROM brands WHERE name = '黄焖鸡米饭' LIMIT 1)),
('兰州拉面', '清汤牛肉面', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=lanzhou%20beef%20noodles%20takeout&image_size=square', (SELECT id FROM categories WHERE name = '面食' LIMIT 1), '{"calories": 380, "protein": 18, "fat": 12, "carbs": 52}', 4.4, 1800, 88, (SELECT id FROM brands WHERE name = '兰州拉面' LIMIT 1)),
('沙县小吃拌面', '福建特色小吃', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=shaxian%20mixed%20noodles%20takeout&image_size=square', (SELECT id FROM categories WHERE name = '面食' LIMIT 1), '{"calories": 320, "protein": 12, "fat": 15, "carbs": 38}', 4.1, 1200, 78, (SELECT id FROM brands WHERE name = '沙县小吃' LIMIT 1)),
('重庆小面', '麻辣鲜香的重庆面条', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=chongqing%20spicy%20noodles%20takeout&image_size=square', (SELECT id FROM categories WHERE name = '面食' LIMIT 1), '{"calories": 350, "protein": 15, "fat": 18, "carbs": 35}', 4.5, 1500, 85, (SELECT id FROM brands WHERE name = '重庆小面' LIMIT 1)),
('煲仔饭', '广式经典，米饭香糯', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=clay%20pot%20rice%20cantonese%20takeout&image_size=square', (SELECT id FROM categories WHERE name = '粤菜' LIMIT 1), '{"calories": 420, "protein": 20, "fat": 16, "carbs": 52}', 4.4, 980, 82, (SELECT id FROM brands WHERE name = '煲仔饭' LIMIT 1));

-- 减脂健康菜品 (100个)
INSERT INTO dishes (name, description, image_url, category_id, nutrition_facts, avg_rating, review_count, popularity_score, brand_id) VALUES
('蒸蛋白', '高蛋白低脂肪', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=steamed%20egg%20white%20healthy&image_size=square', (SELECT id FROM categories WHERE name = '健康餐' LIMIT 1), '{"calories": 60, "protein": 12, "fat": 0, "carbs": 1}', 4.2, 380, 65, (SELECT id FROM brands WHERE name = '轻食工坊' LIMIT 1)),
('水煮鸡胸肉', '减脂必备，高蛋白', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=boiled%20chicken%20breast%20diet&image_size=square', (SELECT id FROM categories WHERE name = '健康餐' LIMIT 1), '{"calories": 120, "protein": 25, "fat": 2, "carbs": 0}', 4.0, 520, 72, (SELECT id FROM brands WHERE name = '轻食工坊' LIMIT 1)),
('蒸西兰花', '低卡高纤维蔬菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=steamed%20broccoli%20healthy%20diet&image_size=square', (SELECT id FROM categories WHERE name = '素食' LIMIT 1), '{"calories": 30, "protein": 3, "fat": 0, "carbs": 6}', 3.9, 280, 55, (SELECT id FROM brands WHERE name = '轻食工坊' LIMIT 1)),
('水煮菠菜', '补铁蔬菜，低热量', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=boiled%20spinach%20healthy%20diet&image_size=square', (SELECT id FROM categories WHERE name = '素食' LIMIT 1), '{"calories": 25, "protein": 3, "fat": 0, "carbs": 4}', 3.8, 220, 48, (SELECT id FROM brands WHERE name = '轻食工坊' LIMIT 1)),
('蒸蛋羹', '嫩滑低脂', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=steamed%20egg%20custard%20diet&image_size=square', (SELECT id FROM categories WHERE name = '健康餐' LIMIT 1), '{"calories": 80, "protein": 8, "fat": 4, "carbs": 2}', 4.1, 420, 62, (SELECT id FROM brands WHERE name = '轻食工坊' LIMIT 1)),
('清蒸鱼', '高蛋白低脂肪', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=steamed%20fish%20healthy%20diet&image_size=square', (SELECT id FROM categories WHERE name = '健康餐' LIMIT 1), '{"calories": 110, "protein": 22, "fat": 2, "carbs": 0}', 4.3, 680, 78, (SELECT id FROM brands WHERE name = '轻食工坊' LIMIT 1)),
('水煮虾', '高蛋白海鲜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=boiled%20shrimp%20healthy%20diet&image_size=square', (SELECT id FROM categories WHERE name = '健康餐' LIMIT 1), '{"calories": 90, "protein": 18, "fat": 1, "carbs": 1}', 4.2, 520, 72, (SELECT id FROM brands WHERE name = '轻食工坊' LIMIT 1)),
('蒸蛋白配蔬菜', '营养均衡减脂餐', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=egg%20white%20vegetables%20diet%20meal&image_size=square', (SELECT id FROM categories WHERE name = '健康餐' LIMIT 1), '{"calories": 100, "protein": 15, "fat": 1, "carbs": 8}', 4.1, 380, 65, (SELECT id FROM brands WHERE name = '轻食工坊' LIMIT 1)),
('紫薯', '低脂碳水化合物', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=purple%20sweet%20potato%20healthy&image_size=square', (SELECT id FROM categories WHERE name = '健康餐' LIMIT 1), '{"calories": 120, "protein": 2, "fat": 0, "carbs": 28}', 4.0, 320, 58, (SELECT id FROM brands WHERE name = '轻食工坊' LIMIT 1)),
('燕麦粥', '高纤维早餐', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=oatmeal%20porridge%20healthy%20breakfast&image_size=square', (SELECT id FROM categories WHERE name = '健康餐' LIMIT 1), '{"calories": 150, "protein": 5, "fat": 3, "carbs": 27}', 4.2, 450, 68, (SELECT id FROM brands WHERE name = '轻食工坊' LIMIT 1));

-- 更多川菜 (继续添加90个)
INSERT INTO dishes (name, description, image_url, category_id, nutrition_facts, avg_rating, review_count, popularity_score, brand_id) VALUES
('水煮牛肉', '麻辣鲜香的川菜经典', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=sichuan%20boiled%20beef%20spicy&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 300, "protein": 28, "fat": 18, "carbs": 6}', 4.6, 1100, 92, (SELECT id FROM brands WHERE name = '川味轩' LIMIT 1)),
('干煸豆角', '川菜经典素菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=dry%20fried%20green%20beans%20sichuan&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 180, "protein": 6, "fat": 12, "carbs": 15}', 4.3, 680, 75, (SELECT id FROM brands WHERE name = '川味轩' LIMIT 1)),
('蚂蚁上树', '川菜经典粉丝菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=ants%20climbing%20tree%20sichuan%20noodles&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 250, "protein": 12, "fat": 15, "carbs": 20}', 4.2, 520, 68, (SELECT id FROM brands WHERE name = '川味轩' LIMIT 1)),
('红油抄手', '川式馄饨', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=red%20oil%20wontons%20sichuan&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 320, "protein": 15, "fat": 18, "carbs": 28}', 4.4, 780, 82, (SELECT id FROM brands WHERE name = '川味轩' LIMIT 1)),
('钟水饺', '川菜经典小吃', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=zhong%20dumplings%20sichuan%20snack&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 280, "protein": 12, "fat": 15, "carbs": 25}', 4.3, 620, 72, (SELECT id FROM brands WHERE name = '川味轩' LIMIT 1));

-- 更多湘菜 (继续添加70个)
INSERT INTO dishes (name, description, image_url, category_id, nutrition_facts, avg_rating, review_count, popularity_score, brand_id) VALUES
('湘西腊肉', '烟熏香味浓郁', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=xiangxi%20smoked%20bacon%20hunan&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 420, "protein": 22, "fat": 32, "carbs": 8}', 4.5, 650, 78, (SELECT id FROM brands WHERE name = '湘味楼' LIMIT 1)),
('酸辣土豆丝', '开胃下饭的经典菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=sour%20spicy%20potato%20shreds%20hunan&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 150, "protein": 3, "fat": 8, "carbs": 18}', 4.2, 480, 65, (SELECT id FROM brands WHERE name = '湘味楼' LIMIT 1)),
('湘式小炒肉', '湘菜家常菜代表', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=hunan%20style%20stir%20fried%20pork&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 350, "protein": 20, "fat": 25, "carbs": 12}', 4.4, 720, 80, (SELECT id FROM brands WHERE name = '湘味楼' LIMIT 1)),
('剁椒蒸蛋', '湘菜特色蒸蛋', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=chopped%20pepper%20steamed%20egg%20hunan&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 180, "protein": 12, "fat": 12, "carbs": 5}', 4.1, 380, 62, (SELECT id FROM brands WHERE name = '湘味楼' LIMIT 1)),
('湘西酸菜', '开胃解腻的酸菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=xiangxi%20pickled%20vegetables%20hunan&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 80, "protein": 2, "fat": 3, "carbs": 12}', 4.0, 320, 55, (SELECT id FROM brands WHERE name = '湘味楼' LIMIT 1));

-- 更多校园食堂菜品 (继续添加192个)
INSERT INTO dishes (name, description, image_url, category_id, nutrition_facts, avg_rating, review_count, popularity_score, brand_id) VALUES
('宫保鸡丁', '食堂版宫保鸡丁', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=kung%20pao%20chicken%20cafeteria%20style&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 280, "protein": 18, "fat": 16, "carbs": 18}', 4.0, 650, 72, (SELECT id FROM brands WHERE name = '海南大学食堂' LIMIT 1)),
('鱼香茄子', '下饭神器', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=fish%20fragrant%20eggplant%20cafeteria&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 220, "protein": 5, "fat": 15, "carbs": 18}', 3.9, 480, 65, (SELECT id FROM brands WHERE name = '海南大学食堂' LIMIT 1)),
('酸辣汤', '开胃汤品', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=hot%20sour%20soup%20cafeteria&image_size=square', (SELECT id FROM categories WHERE name = '汤品' LIMIT 1), '{"calories": 80, "protein": 4, "fat": 3, "carbs": 10}', 4.1, 520, 68, (SELECT id FROM brands WHERE name = '海南大学食堂' LIMIT 1)),
('冬瓜汤', '清淡汤品', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=winter%20melon%20soup%20cafeteria&image_size=square', (SELECT id FROM categories WHERE name = '汤品' LIMIT 1), '{"calories": 50, "protein": 2, "fat": 1, "carbs": 8}', 3.8, 320, 52, (SELECT id FROM brands WHERE name = '海南大学食堂' LIMIT 1)),
('紫菜蛋花汤', '营养汤品', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=seaweed%20egg%20drop%20soup%20cafeteria&image_size=square', (SELECT id FROM categories WHERE name = '汤品' LIMIT 1), '{"calories": 60, "protein": 5, "fat": 3, "carbs": 4}', 4.0, 420, 62, (SELECT id FROM brands WHERE name = '海南大学食堂' LIMIT 1));

-- 更多外卖热门菜品 (继续添加195个)
INSERT INTO dishes (name, description, image_url, category_id, nutrition_facts, avg_rating, review_count, popularity_score, brand_id) VALUES
('麻辣香锅', '外卖热门，麻辣过瘾', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=spicy%20hot%20pot%20takeout&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 450, "protein": 20, "fat": 28, "carbs": 35}', 4.5, 2200, 92, (SELECT id FROM brands WHERE name = '麻辣香锅' LIMIT 1)),
('酸菜鱼', '外卖版酸菜鱼', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=pickled%20fish%20takeout%20delivery&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 320, "protein": 25, "fat": 15, "carbs": 18}', 4.4, 1800, 88, (SELECT id FROM brands WHERE name = '酸菜鱼' LIMIT 1)),
('麻辣烫', '街头小吃经典', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=malatang%20spicy%20soup%20takeout&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 280, "protein": 15, "fat": 18, "carbs": 20}', 4.3, 1500, 85, (SELECT id FROM brands WHERE name = '麻辣烫' LIMIT 1)),
('烤鱼', '外卖烤鱼', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=grilled%20fish%20takeout%20spicy&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 380, "protein": 28, "fat": 22, "carbs": 15}', 4.6, 1200, 82, (SELECT id FROM brands WHERE name = '烤鱼' LIMIT 1)),
('火锅', '外卖小火锅', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=hot%20pot%20takeout%20individual&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 420, "protein": 22, "fat": 25, "carbs": 28}', 4.7, 2800, 95, (SELECT id FROM brands WHERE name = '小火锅' LIMIT 1));

-- 更多减脂健康菜品 (继续添加90个)
INSERT INTO dishes (name, description, image_url, category_id, nutrition_facts, avg_rating, review_count, popularity_score, brand_id) VALUES
('蒸南瓜', '低卡甜味蔬菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=steamed%20pumpkin%20healthy%20diet&image_size=square', (SELECT id FROM categories WHERE name = '健康餐' LIMIT 1), '{"calories": 80, "protein": 2, "fat": 0, "carbs": 18}', 3.9, 280, 52, (SELECT id FROM brands WHERE name = '轻食工坊' LIMIT 1)),
('水煮白菜', '超低卡蔬菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=boiled%20cabbage%20diet%20healthy&image_size=square', (SELECT id FROM categories WHERE name = '素食' LIMIT 1), '{"calories": 20, "protein": 2, "fat": 0, "carbs": 4}', 3.7, 180, 42, (SELECT id FROM brands WHERE name = '轻食工坊' LIMIT 1)),
('蒸胡萝卜', '富含维生素A', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=steamed%20carrots%20healthy%20diet&image_size=square', (SELECT id FROM categories WHERE name = '素食' LIMIT 1), '{"calories": 40, "protein": 1, "fat": 0, "carbs": 9}', 3.8, 220, 48, (SELECT id FROM brands WHERE name = '轻食工坊' LIMIT 1)),
('水煮豆腐', '高蛋白低脂', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=boiled%20tofu%20healthy%20diet&image_size=square', (SELECT id FROM categories WHERE name = '健康餐' LIMIT 1), '{"calories": 70, "protein": 8, "fat": 4, "carbs": 2}', 4.0, 320, 58, (SELECT id FROM brands WHERE name = '轻食工坊' LIMIT 1)),
('蒸冬瓜', '利水消肿', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=steamed%20winter%20melon%20diet&image_size=square', (SELECT id FROM categories WHERE name = '素食' LIMIT 1), '{"calories": 15, "protein": 1, "fat": 0, "carbs": 3}', 3.6, 150, 38, (SELECT id FROM brands WHERE name = '轻食工坊' LIMIT 1));