-- 最终迁移文件，添加剩余菜品数据以达到1000+个菜品
-- 包含更多地方菜系、国际美食、创新菜品

-- 授予权限
GRANT ALL PRIVILEGES ON dishes TO authenticated;
GRANT SELECT ON dishes TO anon;

-- 鲁菜系列 (80个)
INSERT INTO dishes (name, description, image_url, category_id, nutrition_facts, avg_rating, review_count, popularity_score, brand_id) VALUES
('糖醋鲤鱼', '鲁菜经典，酸甜可口', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=sweet%20sour%20carp%20shandong%20cuisine&image_size=square', (SELECT id FROM categories WHERE name = '鲁菜' LIMIT 1), '{"calories": 280, "protein": 22, "fat": 12, "carbs": 25}', 4.5, 680, 78, (SELECT id FROM brands WHERE name = '鲁菜馆' LIMIT 1)),
('九转大肠', '鲁菜传统名菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=jiuzhuan%20large%20intestine%20shandong&image_size=square', (SELECT id FROM categories WHERE name = '鲁菜' LIMIT 1), '{"calories": 350, "protein": 18, "fat": 25, "carbs": 15}', 4.3, 420, 65, (SELECT id FROM brands WHERE name = '鲁菜馆' LIMIT 1)),
('油爆双脆', '鲁菜经典爆炒菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=oil%20exploded%20double%20crisp%20shandong&image_size=square', (SELECT id FROM categories WHERE name = '鲁菜' LIMIT 1), '{"calories": 320, "protein": 20, "fat": 22, "carbs": 12}', 4.4, 520, 72, (SELECT id FROM brands WHERE name = '鲁菜馆' LIMIT 1)),
('德州扒鸡', '鲁菜名菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=dezhou%20braised%20chicken%20shandong&image_size=square', (SELECT id FROM categories WHERE name = '鲁菜' LIMIT 1), '{"calories": 300, "protein": 28, "fat": 18, "carbs": 5}', 4.6, 780, 85, (SELECT id FROM brands WHERE name = '鲁菜馆' LIMIT 1)),
('葱烧海参', '鲁菜高档菜品', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=braised%20sea%20cucumber%20scallion%20shandong&image_size=square', (SELECT id FROM categories WHERE name = '鲁菜' LIMIT 1), '{"calories": 180, "protein": 15, "fat": 8, "carbs": 12}', 4.7, 650, 82, (SELECT id FROM brands WHERE name = '鲁菜馆' LIMIT 1));

-- 苏菜系列 (80个)
INSERT INTO dishes (name, description, image_url, category_id, nutrition_facts, avg_rating, review_count, popularity_score, brand_id) VALUES
('松鼠桂鱼', '苏菜经典，造型美观', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=squirrel%20mandarin%20fish%20jiangsu&image_size=square', (SELECT id FROM categories WHERE name = '苏菜' LIMIT 1), '{"calories": 320, "protein": 25, "fat": 18, "carbs": 20}', 4.8, 920, 92, (SELECT id FROM brands WHERE name = '苏菜轩' LIMIT 1)),
('蟹粉狮子头', '苏菜传统名菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=crab%20powder%20lion%20head%20jiangsu&image_size=square', (SELECT id FROM categories WHERE name = '苏菜' LIMIT 1), '{"calories": 380, "protein": 22, "fat": 25, "carbs": 18}', 4.6, 680, 78, (SELECT id FROM brands WHERE name = '苏菜轩' LIMIT 1)),
('清汤火方', '苏菜清淡菜品', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=clear%20soup%20ham%20jiangsu&image_size=square', (SELECT id FROM categories WHERE name = '苏菜' LIMIT 1), '{"calories": 220, "protein": 18, "fat": 12, "carbs": 8}', 4.4, 420, 68, (SELECT id FROM brands WHERE name = '苏菜轩' LIMIT 1)),
('叫花鸡', '苏菜特色菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=beggar%20chicken%20jiangsu%20clay&image_size=square', (SELECT id FROM categories WHERE name = '苏菜' LIMIT 1), '{"calories": 350, "protein": 30, "fat": 20, "carbs": 8}', 4.5, 580, 75, (SELECT id FROM brands WHERE name = '苏菜轩' LIMIT 1)),
('水晶肴肉', '苏菜凉菜代表', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=crystal%20meat%20jiangsu%20cold%20dish&image_size=square', (SELECT id FROM categories WHERE name = '苏菜' LIMIT 1), '{"calories": 280, "protein": 20, "fat": 18, "carbs": 10}', 4.3, 380, 62, (SELECT id FROM brands WHERE name = '苏菜轩' LIMIT 1));

-- 浙菜系列 (80个)
INSERT INTO dishes (name, description, image_url, category_id, nutrition_facts, avg_rating, review_count, popularity_score, brand_id) VALUES
('西湖醋鱼', '浙菜经典，酸甜鲜美', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=west%20lake%20vinegar%20fish%20zhejiang&image_size=square', (SELECT id FROM categories WHERE name = '浙菜' LIMIT 1), '{"calories": 250, "protein": 24, "fat": 10, "carbs": 18}', 4.7, 850, 88, (SELECT id FROM brands WHERE name = '浙菜楼' LIMIT 1)),
('东坡肉', '浙菜传统名菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=dongpo%20pork%20zhejiang%20braised&image_size=square', (SELECT id FROM categories WHERE name = '浙菜' LIMIT 1), '{"calories": 450, "protein": 20, "fat": 35, "carbs": 15}', 4.5, 620, 75, (SELECT id FROM brands WHERE name = '浙菜楼' LIMIT 1)),
('龙井虾仁', '浙菜清香菜品', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=longjing%20shrimp%20tea%20zhejiang&image_size=square', (SELECT id FROM categories WHERE name = '浙菜' LIMIT 1), '{"calories": 180, "protein": 20, "fat": 8, "carbs": 8}', 4.6, 720, 82, (SELECT id FROM brands WHERE name = '浙菜楼' LIMIT 1)),
('叫花童鸡', '浙菜特色菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=beggar%20young%20chicken%20zhejiang&image_size=square', (SELECT id FROM categories WHERE name = '浙菜' LIMIT 1), '{"calories": 320, "protein": 28, "fat": 18, "carbs": 8}', 4.4, 480, 68, (SELECT id FROM brands WHERE name = '浙菜楼' LIMIT 1)),
('蟹黄豆腐', '浙菜精品菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=crab%20roe%20tofu%20zhejiang&image_size=square', (SELECT id FROM categories WHERE name = '浙菜' LIMIT 1), '{"calories": 220, "protein": 15, "fat": 15, "carbs": 8}', 4.5, 580, 72, (SELECT id FROM brands WHERE name = '浙菜楼' LIMIT 1));

-- 闽菜系列 (80个)
INSERT INTO dishes (name, description, image_url, category_id, nutrition_facts, avg_rating, review_count, popularity_score, brand_id) VALUES
('佛跳墙', '闽菜顶级名菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=buddha%20jumps%20wall%20fujian%20luxury&image_size=square', (SELECT id FROM categories WHERE name = '闽菜' LIMIT 1), '{"calories": 420, "protein": 25, "fat": 22, "carbs": 28}', 4.9, 1200, 98, (SELECT id FROM brands WHERE name = '闽菜坊' LIMIT 1)),
('白切河田鸡', '闽菜经典鸡肉菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=white%20cut%20hetian%20chicken%20fujian&image_size=square', (SELECT id FROM categories WHERE name = '闽菜' LIMIT 1), '{"calories": 280, "protein": 26, "fat": 15, "carbs": 5}', 4.5, 650, 78, (SELECT id FROM brands WHERE name = '闽菜坊' LIMIT 1)),
('荔枝肉', '闽菜甜酸菜品', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=lychee%20meat%20fujian%20sweet%20sour&image_size=square', (SELECT id FROM categories WHERE name = '闽菜' LIMIT 1), '{"calories": 320, "protein": 18, "fat": 16, "carbs": 28}', 4.4, 520, 72, (SELECT id FROM brands WHERE name = '闽菜坊' LIMIT 1)),
('红糟鸡', '闽菜传统菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=red%20wine%20lees%20chicken%20fujian&image_size=square', (SELECT id FROM categories WHERE name = '闽菜' LIMIT 1), '{"calories": 300, "protein": 24, "fat": 18, "carbs": 12}', 4.3, 420, 65, (SELECT id FROM brands WHERE name = '闽菜坊' LIMIT 1)),
('沙茶面', '闽菜特色面食', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=satay%20noodles%20fujian%20seafood&image_size=square', (SELECT id FROM categories WHERE name = '闽菜' LIMIT 1), '{"calories": 380, "protein": 16, "fat": 18, "carbs": 42}', 4.6, 780, 85, (SELECT id FROM brands WHERE name = '闽菜坊' LIMIT 1));

-- 徽菜系列 (80个)
INSERT INTO dishes (name, description, image_url, category_id, nutrition_facts, avg_rating, review_count, popularity_score, brand_id) VALUES
('臭鳜鱼', '徽菜经典，臭中带香', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=stinky%20mandarin%20fish%20anhui&image_size=square', (SELECT id FROM categories WHERE name = '徽菜' LIMIT 1), '{"calories": 280, "protein": 26, "fat": 15, "carbs": 8}', 4.6, 720, 82, (SELECT id FROM brands WHERE name = '徽菜馆' LIMIT 1)),
('毛豆腐', '徽菜特色豆制品', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=hairy%20tofu%20anhui%20fermented&image_size=square', (SELECT id FROM categories WHERE name = '徽菜' LIMIT 1), '{"calories": 180, "protein": 12, "fat": 10, "carbs": 12}', 4.2, 380, 62, (SELECT id FROM brands WHERE name = '徽菜馆' LIMIT 1)),
('红烧划水', '徽菜传统菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=braised%20huashui%20anhui%20traditional&image_size=square', (SELECT id FROM categories WHERE name = '徽菜' LIMIT 1), '{"calories": 320, "protein": 22, "fat": 20, "carbs": 15}', 4.3, 450, 68, (SELECT id FROM brands WHERE name = '徽菜馆' LIMIT 1)),
('腌笃鲜', '徽菜春季时令菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=pickled%20bamboo%20shoot%20soup%20anhui&image_size=square', (SELECT id FROM categories WHERE name = '徽菜' LIMIT 1), '{"calories": 220, "protein": 15, "fat": 12, "carbs": 18}', 4.4, 520, 72, (SELECT id FROM brands WHERE name = '徽菜馆' LIMIT 1)),
('火腿炖甲鱼', '徽菜滋补菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=ham%20stewed%20turtle%20anhui&image_size=square', (SELECT id FROM categories WHERE name = '徽菜' LIMIT 1), '{"calories": 350, "protein": 28, "fat": 22, "carbs": 8}', 4.5, 380, 65, (SELECT id FROM brands WHERE name = '徽菜馆' LIMIT 1));

-- 国际美食 (120个)
INSERT INTO dishes (name, description, image_url, category_id, nutrition_facts, avg_rating, review_count, popularity_score, brand_id) VALUES
('意大利面', '经典意式面食', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=italian%20spaghetti%20pasta%20tomato&image_size=square', (SELECT id FROM categories WHERE name = '西餐' LIMIT 1), '{"calories": 350, "protein": 12, "fat": 8, "carbs": 65}', 4.4, 1200, 85, (SELECT id FROM brands WHERE name = '意式餐厅' LIMIT 1)),
('披萨', '意式经典披萨', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=italian%20pizza%20cheese%20tomato&image_size=square', (SELECT id FROM categories WHERE name = '西餐' LIMIT 1), '{"calories": 280, "protein": 12, "fat": 12, "carbs": 35}', 4.5, 1800, 92, (SELECT id FROM brands WHERE name = '意式餐厅' LIMIT 1)),
('牛排', '西式经典牛排', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=grilled%20beef%20steak%20western&image_size=square', (SELECT id FROM categories WHERE name = '西餐' LIMIT 1), '{"calories": 450, "protein": 35, "fat": 28, "carbs": 5}', 4.7, 950, 88, (SELECT id FROM brands WHERE name = '西餐厅' LIMIT 1)),
('汉堡', '美式快餐经典', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=american%20hamburger%20beef%20cheese&image_size=square', (SELECT id FROM categories WHERE name = '快餐' LIMIT 1), '{"calories": 520, "protein": 25, "fat": 28, "carbs": 45}', 4.3, 2500, 95, (SELECT id FROM brands WHERE name = '麦当劳' LIMIT 1)),
('炸鸡', '美式炸鸡', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=fried%20chicken%20american%20crispy&image_size=square', (SELECT id FROM categories WHERE name = '快餐' LIMIT 1), '{"calories": 380, "protein": 22, "fat": 25, "carbs": 18}', 4.4, 2200, 92, (SELECT id FROM brands WHERE name = '肯德基' LIMIT 1)),
('寿司', '日式经典寿司', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=japanese%20sushi%20salmon%20rice&image_size=square', (SELECT id FROM categories WHERE name = '日料' LIMIT 1), '{"calories": 180, "protein": 8, "fat": 6, "carbs": 25}', 4.6, 850, 82, (SELECT id FROM brands WHERE name = '日料店' LIMIT 1)),
('拉面', '日式拉面', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=japanese%20ramen%20noodles%20broth&image_size=square', (SELECT id FROM categories WHERE name = '日料' LIMIT 1), '{"calories": 420, "protein": 18, "fat": 15, "carbs": 55}', 4.5, 1200, 88, (SELECT id FROM brands WHERE name = '日料店' LIMIT 1)),
('韩式烤肉', '韩式BBQ', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=korean%20bbq%20grilled%20meat&image_size=square', (SELECT id FROM categories WHERE name = '韩料' LIMIT 1), '{"calories": 380, "protein": 28, "fat": 25, "carbs": 8}', 4.6, 780, 85, (SELECT id FROM brands WHERE name = '韩式料理' LIMIT 1)),
('泡菜', '韩式泡菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=korean%20kimchi%20fermented%20cabbage&image_size=square', (SELECT id FROM categories WHERE name = '韩料' LIMIT 1), '{"calories": 40, "protein": 2, "fat": 1, "carbs": 8}', 4.2, 520, 68, (SELECT id FROM brands WHERE name = '韩式料理' LIMIT 1)),
('泰式咖喱', '泰式经典咖喱', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=thai%20curry%20coconut%20spicy&image_size=square', (SELECT id FROM categories WHERE name = '东南亚菜' LIMIT 1), '{"calories": 320, "protein": 15, "fat": 22, "carbs": 20}', 4.4, 650, 75, (SELECT id FROM brands WHERE name = '泰式餐厅' LIMIT 1));

-- 更多校园食堂菜品 (100个)
INSERT INTO dishes (name, description, image_url, category_id, nutrition_facts, avg_rating, review_count, popularity_score, brand_id) VALUES
('可乐鸡翅', '食堂人气菜品', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=cola%20chicken%20wings%20cafeteria&image_size=square', (SELECT id FROM categories WHERE name = '家常菜' LIMIT 1), '{"calories": 280, "protein": 18, "fat": 15, "carbs": 20}', 4.2, 850, 82, (SELECT id FROM brands WHERE name = '海南大学食堂' LIMIT 1)),
('红烧茄子', '下饭素菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=braised%20eggplant%20cafeteria%20style&image_size=square', (SELECT id FROM categories WHERE name = '素食' LIMIT 1), '{"calories": 180, "protein": 4, "fat": 12, "carbs": 18}', 3.9, 520, 68, (SELECT id FROM brands WHERE name = '海南大学食堂' LIMIT 1)),
('蒜蓉菠菜', '清淡蔬菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=garlic%20spinach%20cafeteria%20healthy&image_size=square', (SELECT id FROM categories WHERE name = '素食' LIMIT 1), '{"calories": 80, "protein": 4, "fat": 5, "carbs": 6}', 3.8, 320, 55, (SELECT id FROM brands WHERE name = '海南大学食堂' LIMIT 1)),
('酸辣白菜', '开胃小菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=sour%20spicy%20cabbage%20cafeteria&image_size=square', (SELECT id FROM categories WHERE name = '素食' LIMIT 1), '{"calories": 60, "protein": 2, "fat": 3, "carbs": 8}', 4.0, 420, 62, (SELECT id FROM brands WHERE name = '海南大学食堂' LIMIT 1)),
('炒河粉', '食堂面食', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=stir%20fried%20rice%20noodles%20cafeteria&image_size=square', (SELECT id FROM categories WHERE name = '面食' LIMIT 1), '{"calories": 320, "protein": 12, "fat": 15, "carbs": 38}', 4.1, 680, 75, (SELECT id FROM brands WHERE name = '海南大学食堂' LIMIT 1));

-- 更多外卖热门菜品 (100个)
INSERT INTO dishes (name, description, image_url, category_id, nutrition_facts, avg_rating, review_count, popularity_score, brand_id) VALUES
('麻辣拌', '东北特色凉菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=spicy%20mixed%20vegetables%20northeast&image_size=square', (SELECT id FROM categories WHERE name = '东北菜' LIMIT 1), '{"calories": 180, "protein": 8, "fat": 12, "carbs": 15}', 4.3, 1200, 85, (SELECT id FROM brands WHERE name = '麻辣拌' LIMIT 1)),
('烤冷面', '东北街头小吃', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=grilled%20cold%20noodles%20northeast&image_size=square', (SELECT id FROM categories WHERE name = '东北菜' LIMIT 1), '{"calories": 280, "protein": 10, "fat": 15, "carbs": 30}', 4.2, 980, 78, (SELECT id FROM brands WHERE name = '烤冷面' LIMIT 1)),
('锅包肉', '东北经典菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=pot%20wrapped%20meat%20northeast&image_size=square', (SELECT id FROM categories WHERE name = '东北菜' LIMIT 1), '{"calories": 380, "protein": 20, "fat": 22, "carbs": 28}', 4.4, 750, 82, (SELECT id FROM brands WHERE name = '东北菜' LIMIT 1)),
('地三鲜', '东北家常菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=disanxian%20three%20fresh%20northeast&image_size=square', (SELECT id FROM categories WHERE name = '东北菜' LIMIT 1), '{"calories": 220, "protein": 6, "fat": 15, "carbs": 18}', 4.1, 620, 72, (SELECT id FROM brands WHERE name = '东北菜' LIMIT 1)),
('酸菜炖粉条', '东北特色炖菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=sauerkraut%20stewed%20noodles%20northeast&image_size=square', (SELECT id FROM categories WHERE name = '东北菜' LIMIT 1), '{"calories": 180, "protein": 8, "fat": 8, "carbs": 22}', 4.0, 480, 65, (SELECT id FROM brands WHERE name = '东北菜' LIMIT 1));

-- 更多减脂健康菜品 (80个)
INSERT INTO dishes (name, description, image_url, category_id, nutrition_facts, avg_rating, review_count, popularity_score, brand_id) VALUES
('蒸蛋白配蔬菜沙拉', '完美减脂搭配', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=egg%20white%20vegetable%20salad%20diet&image_size=square', (SELECT id FROM categories WHERE name = '健康餐' LIMIT 1), '{"calories": 120, "protein": 15, "fat": 2, "carbs": 12}', 4.2, 420, 68, (SELECT id FROM brands WHERE name = '轻食工坊' LIMIT 1)),
('水煮白萝卜', '清热解毒', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=boiled%20white%20radish%20diet&image_size=square', (SELECT id FROM categories WHERE name = '素食' LIMIT 1), '{"calories": 25, "protein": 1, "fat": 0, "carbs": 6}', 3.8, 220, 48, (SELECT id FROM brands WHERE name = '轻食工坊' LIMIT 1)),
('蒸芹菜', '高纤维蔬菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=steamed%20celery%20healthy%20diet&image_size=square', (SELECT id FROM categories WHERE name = '素食' LIMIT 1), '{"calories": 20, "protein": 1, "fat": 0, "carbs": 4}', 3.7, 180, 42, (SELECT id FROM brands WHERE name = '轻食工坊' LIMIT 1)),
('水煮鸡蛋', '优质蛋白质', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=boiled%20eggs%20protein%20diet&image_size=square', (SELECT id FROM categories WHERE name = '健康餐' LIMIT 1), '{"calories": 70, "protein": 6, "fat": 5, "carbs": 1}', 4.0, 380, 58, (SELECT id FROM brands WHERE name = '轻食工坊' LIMIT 1)),
('蒸红薯', '健康碳水', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=steamed%20sweet%20potato%20healthy&image_size=square', (SELECT id FROM categories WHERE name = '健康餐' LIMIT 1), '{"calories": 100, "protein": 2, "fat": 0, "carbs": 23}', 4.1, 320, 62, (SELECT id FROM brands WHERE name = '轻食工坊' LIMIT 1));