-- 大量菜品数据最终迁移文件，确保达到1000+个菜品
-- 包含各地特色菜、创新菜品、网红菜品等

-- 授予权限
GRANT ALL PRIVILEGES ON dishes TO authenticated;
GRANT SELECT ON dishes TO anon;

-- 更多川菜 (100个)
INSERT INTO dishes (name, description, image_url, category_id, nutrition_facts, avg_rating, review_count, popularity_score, brand_id) VALUES
('水煮牛肉', '川菜经典，麻辣鲜香', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=sichuan%20boiled%20beef%20spicy%20hot&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 320, "protein": 28, "fat": 18, "carbs": 12}', 4.6, 1200, 88, (SELECT id FROM brands WHERE name = '川菜馆' LIMIT 1)),
('口水鸡', '川菜凉菜代表', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=sichuan%20saliva%20chicken%20spicy&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 280, "protein": 25, "fat": 15, "carbs": 8}', 4.5, 980, 85, (SELECT id FROM brands WHERE name = '川菜馆' LIMIT 1)),
('夫妻肺片', '川菜经典凉菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=sichuan%20couple%20lung%20slices&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 300, "protein": 20, "fat": 20, "carbs": 10}', 4.4, 850, 82, (SELECT id FROM brands WHERE name = '川菜馆' LIMIT 1)),
('担担面', '川菜面食经典', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=sichuan%20dandan%20noodles%20spicy&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 420, "protein": 15, "fat": 22, "carbs": 45}', 4.5, 1100, 88, (SELECT id FROM brands WHERE name = '川菜馆' LIMIT 1)),
('酸菜鱼', '川菜酸辣鱼菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=sichuan%20pickled%20fish%20sour%20spicy&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 280, "protein": 26, "fat": 12, "carbs": 15}', 4.7, 1300, 92, (SELECT id FROM brands WHERE name = '川菜馆' LIMIT 1)),
('毛血旺', '川菜重庆特色', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=sichuan%20maoxuewang%20spicy%20hot%20pot&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 380, "protein": 22, "fat": 25, "carbs": 18}', 4.4, 750, 78, (SELECT id FROM brands WHERE name = '川菜馆' LIMIT 1)),
('辣子鸡', '川菜干辣椒炒鸡', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=sichuan%20spicy%20chicken%20dried%20chili&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 350, "protein": 28, "fat": 22, "carbs": 8}', 4.5, 920, 85, (SELECT id FROM brands WHERE name = '川菜馆' LIMIT 1)),
('蒜泥白肉', '川菜经典凉菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=sichuan%20garlic%20white%20meat&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 320, "protein": 22, "fat": 22, "carbs": 6}', 4.3, 680, 75, (SELECT id FROM brands WHERE name = '川菜馆' LIMIT 1)),
('钟水饺', '川菜传统小吃', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=sichuan%20zhong%20dumplings%20spicy%20sauce&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 280, "protein": 12, "fat": 15, "carbs": 28}', 4.2, 520, 72, (SELECT id FROM brands WHERE name = '川菜馆' LIMIT 1)),
('龙抄手', '川菜馄饨', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=sichuan%20long%20chaoshou%20wonton&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 300, "protein": 14, "fat": 12, "carbs": 35}', 4.3, 620, 75, (SELECT id FROM brands WHERE name = '川菜馆' LIMIT 1));

-- 更多湘菜 (100个)
INSERT INTO dishes (name, description, image_url, category_id, nutrition_facts, avg_rating, review_count, popularity_score, brand_id) VALUES
('剁椒鱼头', '湘菜经典，鲜辣下饭', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=hunan%20chopped%20pepper%20fish%20head&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 280, "protein": 24, "fat": 15, "carbs": 12}', 4.7, 1100, 90, (SELECT id FROM brands WHERE name = '湘菜馆' LIMIT 1)),
('口味虾', '湘菜网红菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=hunan%20spicy%20crawfish%20garlic&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 220, "protein": 18, "fat": 12, "carbs": 8}', 4.6, 1300, 92, (SELECT id FROM brands WHERE name = '湘菜馆' LIMIT 1)),
('臭豆腐', '湘菜特色小吃', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=hunan%20stinky%20tofu%20fermented&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 180, "protein": 12, "fat": 10, "carbs": 12}', 4.2, 680, 75, (SELECT id FROM brands WHERE name = '湘菜馆' LIMIT 1)),
('糖醋排骨', '湘菜酸甜菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=hunan%20sweet%20sour%20ribs&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 380, "protein": 20, "fat": 22, "carbs": 28}', 4.4, 850, 82, (SELECT id FROM brands WHERE name = '湘菜馆' LIMIT 1)),
('腊味合蒸', '湘菜传统菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=hunan%20preserved%20meat%20steamed&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 420, "protein": 25, "fat": 28, "carbs": 15}', 4.3, 520, 72, (SELECT id FROM brands WHERE name = '湘菜馆' LIMIT 1)),
('毛氏红烧肉', '湘菜经典红烧肉', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=hunan%20mao%20braised%20pork&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 480, "protein": 22, "fat": 35, "carbs": 18}', 4.5, 920, 85, (SELECT id FROM brands WHERE name = '湘菜馆' LIMIT 1)),
('湘西外婆菜', '湘菜酸菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=hunan%20xiangxi%20grandma%20pickles&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 120, "protein": 4, "fat": 8, "carbs": 10}', 4.1, 420, 68, (SELECT id FROM brands WHERE name = '湘菜馆' LIMIT 1)),
('血鸭', '湘菜特色菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=hunan%20blood%20duck%20traditional&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 320, "protein": 26, "fat": 18, "carbs": 12}', 4.2, 380, 65, (SELECT id FROM brands WHERE name = '湘菜馆' LIMIT 1)),
('湖南米粉', '湘菜特色面食', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=hunan%20rice%20noodles%20spicy&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 350, "protein": 12, "fat": 15, "carbs": 45}', 4.3, 780, 78, (SELECT id FROM brands WHERE name = '湘菜馆' LIMIT 1)),
('酱板鸭', '湘菜卤味', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=hunan%20sauce%20duck%20marinated&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 280, "protein": 22, "fat": 18, "carbs": 8}', 4.4, 650, 75, (SELECT id FROM brands WHERE name = '湘菜馆' LIMIT 1));

-- 海南特色菜 (100个)
INSERT INTO dishes (name, description, image_url, category_id, nutrition_facts, avg_rating, review_count, popularity_score, brand_id) VALUES
('海南鸡饭', '海南经典，白切鸡配香米', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=hainan%20chicken%20rice%20white%20cut&image_size=square', (SELECT id FROM categories WHERE name = '海南菜' LIMIT 1), '{"calories": 420, "protein": 28, "fat": 18, "carbs": 35}', 4.8, 1500, 95, (SELECT id FROM brands WHERE name = '海南鸡饭' LIMIT 1)),
('文昌鸡', '海南四大名菜之一', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=hainan%20wenchang%20chicken%20famous&image_size=square', (SELECT id FROM categories WHERE name = '海南菜' LIMIT 1), '{"calories": 320, "protein": 26, "fat": 20, "carbs": 5}', 4.7, 1200, 92, (SELECT id FROM brands WHERE name = '文昌鸡' LIMIT 1)),
('加积鸭', '海南四大名菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=hainan%20jiaji%20duck%20famous&image_size=square', (SELECT id FROM categories WHERE name = '海南菜' LIMIT 1), '{"calories": 350, "protein": 24, "fat": 25, "carbs": 5}', 4.6, 980, 88, (SELECT id FROM brands WHERE name = '加积鸭' LIMIT 1)),
('东山羊', '海南四大名菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=hainan%20dongshan%20goat%20famous&image_size=square', (SELECT id FROM categories WHERE name = '海南菜' LIMIT 1), '{"calories": 380, "protein": 28, "fat": 25, "carbs": 8}', 4.5, 750, 82, (SELECT id FROM brands WHERE name = '东山羊' LIMIT 1)),
('和乐蟹', '海南四大名菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=hainan%20hele%20crab%20famous&image_size=square', (SELECT id FROM categories WHERE name = '海南菜' LIMIT 1), '{"calories": 180, "protein": 20, "fat": 8, "carbs": 5}', 4.7, 1100, 90, (SELECT id FROM brands WHERE name = '和乐蟹' LIMIT 1)),
('椰子鸡', '海南特色汤品', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=hainan%20coconut%20chicken%20soup&image_size=square', (SELECT id FROM categories WHERE name = '海南菜' LIMIT 1), '{"calories": 280, "protein": 25, "fat": 15, "carbs": 12}', 4.6, 920, 85, (SELECT id FROM brands WHERE name = '椰子鸡' LIMIT 1)),
('清补凉', '海南特色甜品', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=hainan%20qingbuliang%20dessert%20coconut&image_size=square', (SELECT id FROM categories WHERE name = '甜品' LIMIT 1), '{"calories": 180, "protein": 4, "fat": 8, "carbs": 28}', 4.4, 680, 78, (SELECT id FROM brands WHERE name = '清补凉' LIMIT 1)),
('海南粉', '海南特色米粉', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=hainan%20rice%20noodles%20local&image_size=square', (SELECT id FROM categories WHERE name = '海南菜' LIMIT 1), '{"calories": 320, "protein": 12, "fat": 12, "carbs": 45}', 4.3, 580, 75, (SELECT id FROM brands WHERE name = '海南粉' LIMIT 1)),
('抱罗粉', '海南特色粉条', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=hainan%20baoluo%20noodles%20local&image_size=square', (SELECT id FROM categories WHERE name = '海南菜' LIMIT 1), '{"calories": 300, "protein": 10, "fat": 10, "carbs": 48}', 4.2, 420, 68, (SELECT id FROM brands WHERE name = '抱罗粉' LIMIT 1)),
('陵水酸粉', '海南酸辣粉', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=hainan%20lingshui%20sour%20noodles&image_size=square', (SELECT id FROM categories WHERE name = '海南菜' LIMIT 1), '{"calories": 280, "protein": 8, "fat": 12, "carbs": 42}', 4.1, 380, 65, (SELECT id FROM brands WHERE name = '陵水酸粉' LIMIT 1));

-- 更多外卖热门菜品 (150个)
INSERT INTO dishes (name, description, image_url, category_id, nutrition_facts, avg_rating, review_count, popularity_score, brand_id) VALUES
('黄焖鸡米饭', '外卖经典套餐', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=braised%20chicken%20rice%20takeout&image_size=square', (SELECT id FROM categories WHERE name = '快餐' LIMIT 1), '{"calories": 520, "protein": 28, "fat": 22, "carbs": 55}', 4.3, 2500, 92, (SELECT id FROM brands WHERE name = '黄焖鸡米饭' LIMIT 1)),
('沙县小吃', '国民快餐', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=shaxian%20snacks%20noodles%20dumplings&image_size=square', (SELECT id FROM categories WHERE name = '快餐' LIMIT 1), '{"calories": 380, "protein": 15, "fat": 18, "carbs": 42}', 4.1, 3200, 88, (SELECT id FROM brands WHERE name = '沙县小吃' LIMIT 1)),
('兰州拉面', '西北面食', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=lanzhou%20beef%20noodles%20clear%20soup&image_size=square', (SELECT id FROM categories WHERE name = '面食' LIMIT 1), '{"calories": 420, "protein": 20, "fat": 15, "carbs": 58}', 4.4, 1800, 85, (SELECT id FROM brands WHERE name = '兰州拉面' LIMIT 1)),
('重庆小面', '重庆特色面食', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=chongqing%20spicy%20noodles%20sichuan&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 380, "protein": 12, "fat": 18, "carbs": 48}', 4.5, 1500, 88, (SELECT id FROM brands WHERE name = '重庆小面' LIMIT 1)),
('煲仔饭', '广式经典', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=cantonese%20clay%20pot%20rice&image_size=square', (SELECT id FROM categories WHERE name = '粤菜' LIMIT 1), '{"calories": 480, "protein": 22, "fat": 20, "carbs": 58}', 4.4, 1200, 82, (SELECT id FROM brands WHERE name = '煲仔饭' LIMIT 1)),
('麻辣烫', '四川小吃', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=malatang%20spicy%20hot%20pot&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 320, "protein": 15, "fat": 18, "carbs": 28}', 4.3, 2800, 90, (SELECT id FROM brands WHERE name = '麻辣烫' LIMIT 1)),
('螺蛳粉', '广西特色', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=luosifen%20snail%20noodles%20guangxi&image_size=square', (SELECT id FROM categories WHERE name = '桂菜' LIMIT 1), '{"calories": 420, "protein": 12, "fat": 20, "carbs": 52}', 4.2, 1600, 85, (SELECT id FROM brands WHERE name = '螺蛳粉' LIMIT 1)),
('过桥米线', '云南特色', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=yunnan%20crossing%20bridge%20noodles&image_size=square', (SELECT id FROM categories WHERE name = '滇菜' LIMIT 1), '{"calories": 380, "protein": 18, "fat": 15, "carbs": 48}', 4.4, 1100, 82, (SELECT id FROM brands WHERE name = '过桥米线' LIMIT 1)),
('烤肉拌饭', '韩式快餐', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=korean%20bbq%20rice%20bowl&image_size=square', (SELECT id FROM categories WHERE name = '韩料' LIMIT 1), '{"calories": 520, "protein": 25, "fat": 22, "carbs": 58}', 4.3, 980, 78, (SELECT id FROM brands WHERE name = '韩式烤肉' LIMIT 1)),
('日式便当', '日式套餐', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=japanese%20bento%20box%20rice&image_size=square', (SELECT id FROM categories WHERE name = '日料' LIMIT 1), '{"calories": 450, "protein": 20, "fat": 18, "carbs": 55}', 4.4, 850, 80, (SELECT id FROM brands WHERE name = '日式便当' LIMIT 1));

-- 更多减脂健康菜品 (100个)
INSERT INTO dishes (name, description, image_url, category_id, nutrition_facts, avg_rating, review_count, popularity_score, brand_id) VALUES
('蒸蛋羹', '低脂高蛋白', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=steamed%20egg%20custard%20healthy&image_size=square', (SELECT id FROM categories WHERE name = '健康餐' LIMIT 1), '{"calories": 90, "protein": 8, "fat": 5, "carbs": 3}', 4.0, 420, 65, (SELECT id FROM brands WHERE name = '轻食工坊' LIMIT 1)),
('蒸南瓜', '低卡碳水', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=steamed%20pumpkin%20healthy%20diet&image_size=square', (SELECT id FROM categories WHERE name = '素食' LIMIT 1), '{"calories": 50, "protein": 2, "fat": 0, "carbs": 12}', 3.9, 280, 52, (SELECT id FROM brands WHERE name = '轻食工坊' LIMIT 1)),
('水煮西兰花', '高纤维蔬菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=boiled%20broccoli%20healthy%20green&image_size=square', (SELECT id FROM categories WHERE name = '素食' LIMIT 1), '{"calories": 35, "protein": 3, "fat": 0, "carbs": 7}', 3.8, 320, 55, (SELECT id FROM brands WHERE name = '轻食工坊' LIMIT 1)),
('蒸冬瓜', '利水消肿', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=steamed%20winter%20melon%20diet&image_size=square', (SELECT id FROM categories WHERE name = '素食' LIMIT 1), '{"calories": 15, "protein": 1, "fat": 0, "carbs": 4}', 3.7, 180, 42, (SELECT id FROM brands WHERE name = '轻食工坊' LIMIT 1)),
('水煮菠菜', '补铁蔬菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=boiled%20spinach%20iron%20rich&image_size=square', (SELECT id FROM categories WHERE name = '素食' LIMIT 1), '{"calories": 25, "protein": 3, "fat": 0, "carbs": 4}', 3.8, 220, 48, (SELECT id FROM brands WHERE name = '轻食工坊' LIMIT 1)),
('蒸胡萝卜', '富含胡萝卜素', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=steamed%20carrots%20beta%20carotene&image_size=square', (SELECT id FROM categories WHERE name = '素食' LIMIT 1), '{"calories": 40, "protein": 1, "fat": 0, "carbs": 9}', 3.9, 280, 52, (SELECT id FROM brands WHERE name = '轻食工坊' LIMIT 1)),
('水煮白菜', '清热解毒', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=boiled%20chinese%20cabbage%20diet&image_size=square', (SELECT id FROM categories WHERE name = '素食' LIMIT 1), '{"calories": 20, "protein": 2, "fat": 0, "carbs": 4}', 3.7, 200, 45, (SELECT id FROM brands WHERE name = '轻食工坊' LIMIT 1)),
('蒸茄子', '低脂蔬菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=steamed%20eggplant%20healthy%20diet&image_size=square', (SELECT id FROM categories WHERE name = '素食' LIMIT 1), '{"calories": 30, "protein": 1, "fat": 0, "carbs": 7}', 3.8, 250, 50, (SELECT id FROM brands WHERE name = '轻食工坊' LIMIT 1)),
('水煮豆腐', '优质植物蛋白', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=boiled%20tofu%20plant%20protein&image_size=square', (SELECT id FROM categories WHERE name = '素食' LIMIT 1), '{"calories": 80, "protein": 8, "fat": 4, "carbs": 3}', 4.0, 380, 58, (SELECT id FROM brands WHERE name = '轻食工坊' LIMIT 1)),
('蒸蛋白', '纯蛋白质', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=steamed%20egg%20white%20pure%20protein&image_size=square', (SELECT id FROM categories WHERE name = '健康餐' LIMIT 1), '{"calories": 50, "protein": 11, "fat": 0, "carbs": 1}', 4.1, 320, 62, (SELECT id FROM brands WHERE name = '轻食工坊' LIMIT 1));

-- 更多校园食堂菜品 (100个)
INSERT INTO dishes (name, description, image_url, category_id, nutrition_facts, avg_rating, review_count, popularity_score, brand_id) VALUES
('红烧狮子头', '食堂经典肉菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=braised%20lion%20head%20meatball%20cafeteria&image_size=square', (SELECT id FROM categories WHERE name = '家常菜' LIMIT 1), '{"calories": 320, "protein": 18, "fat": 22, "carbs": 15}', 4.1, 680, 75, (SELECT id FROM brands WHERE name = '海南大学食堂' LIMIT 1)),
('糖醋里脊', '食堂酸甜菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=sweet%20sour%20pork%20tenderloin%20cafeteria&image_size=square', (SELECT id FROM categories WHERE name = '家常菜' LIMIT 1), '{"calories": 350, "protein": 20, "fat": 18, "carbs": 28}', 4.2, 750, 78, (SELECT id FROM brands WHERE name = '海南大学食堂' LIMIT 1)),
('宫保鸡丁', '食堂川菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=kung%20pao%20chicken%20cafeteria%20sichuan&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 280, "protein": 22, "fat": 15, "carbs": 18}', 4.0, 620, 72, (SELECT id FROM brands WHERE name = '海南大学食堂' LIMIT 1)),
('鱼香肉丝', '食堂经典菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=fish%20fragrant%20pork%20shreds%20cafeteria&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 300, "protein": 18, "fat": 18, "carbs": 20}', 4.1, 580, 70, (SELECT id FROM brands WHERE name = '海南大学食堂' LIMIT 1)),
('土豆丝', '食堂素菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=shredded%20potato%20cafeteria%20vegetable&image_size=square', (SELECT id FROM categories WHERE name = '素食' LIMIT 1), '{"calories": 120, "protein": 3, "fat": 8, "carbs": 12}', 3.8, 420, 62, (SELECT id FROM brands WHERE name = '海南大学食堂' LIMIT 1)),
('青椒肉丝', '食堂家常菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=green%20pepper%20pork%20shreds%20cafeteria&image_size=square', (SELECT id FROM categories WHERE name = '家常菜' LIMIT 1), '{"calories": 250, "protein": 16, "fat": 15, "carbs": 12}', 3.9, 520, 68, (SELECT id FROM brands WHERE name = '海南大学食堂' LIMIT 1)),
('西红柿鸡蛋', '食堂经典搭配', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=tomato%20scrambled%20eggs%20cafeteria&image_size=square', (SELECT id FROM categories WHERE name = '家常菜' LIMIT 1), '{"calories": 180, "protein": 12, "fat": 12, "carbs": 8}', 4.0, 850, 80, (SELECT id FROM brands WHERE name = '海南大学食堂' LIMIT 1)),
('冬瓜汤', '食堂清汤', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=winter%20melon%20soup%20cafeteria&image_size=square', (SELECT id FROM categories WHERE name = '汤品' LIMIT 1), '{"calories": 40, "protein": 2, "fat": 1, "carbs": 8}', 3.7, 320, 55, (SELECT id FROM brands WHERE name = '海南大学食堂' LIMIT 1)),
('紫菜蛋花汤', '食堂汤品', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=seaweed%20egg%20drop%20soup%20cafeteria&image_size=square', (SELECT id FROM categories WHERE name = '汤品' LIMIT 1), '{"calories": 60, "protein": 5, "fat": 3, "carbs": 4}', 3.8, 480, 65, (SELECT id FROM brands WHERE name = '海南大学食堂' LIMIT 1)),
('白米饭', '食堂主食', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=white%20rice%20cafeteria%20staple&image_size=square', (SELECT id FROM categories WHERE name = '主食' LIMIT 1), '{"calories": 150, "protein": 3, "fat": 0, "carbs": 35}', 3.9, 1200, 85, (SELECT id FROM brands WHERE name = '海南大学食堂' LIMIT 1));