-- 添加更多菜品数据以达到1000+个菜品的要求
-- 包含各地特色菜、创新菜品、网红菜品等

-- 授予权限
GRANT ALL PRIVILEGES ON dishes TO authenticated;
GRANT SELECT ON dishes TO anon;

-- 插入川菜菜品 (150个)
INSERT INTO dishes (name, description, image_url, category_id, nutrition_facts, avg_rating, review_count, popularity_score) VALUES
('水煮鱼', '鲜嫩鱼片配麻辣汤底，川菜经典', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Sichuan%20boiled%20fish%20with%20spicy%20broth%20and%20tender%20fish%20slices&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 280, "protein": 25, "fat": 18, "carbs": 8}', 4.6, 1200, 95),
('口水鸡', '麻辣鲜香的凉拌鸡肉', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Sichuan%20saliva%20chicken%20with%20spicy%20sauce&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 220, "protein": 28, "fat": 12, "carbs": 5}', 4.5, 980, 88),
('夫妻肺片', '麻辣牛肉牛杂凉菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Sichuan%20couple%20lung%20slices%20spicy%20beef%20offal&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 260, "protein": 22, "fat": 16, "carbs": 8}', 4.4, 850, 82),
('担担面', '四川传统面条配芝麻酱', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Sichuan%20dandan%20noodles%20with%20sesame%20sauce&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 420, "protein": 15, "fat": 18, "carbs": 52}', 4.7, 1500, 92),
('酸菜鱼', '酸辣开胃的鱼片汤', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Sichuan%20pickled%20cabbage%20fish%20soup&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 240, "protein": 26, "fat": 12, "carbs": 10}', 4.5, 1100, 89),
('毛血旺', '重庆特色麻辣烫', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Chongqing%20maoxuewang%20spicy%20hot%20pot&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 350, "protein": 20, "fat": 25, "carbs": 15}', 4.6, 900, 85),
('辣子鸡', '干辣椒炒鸡丁', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Sichuan%20spicy%20chicken%20with%20dried%20chilies&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 320, "protein": 28, "fat": 20, "carbs": 8}', 4.4, 750, 80),
('回锅肉', '四川传统炒肉片', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Sichuan%20twice%20cooked%20pork%20slices&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 380, "protein": 25, "fat": 28, "carbs": 12}', 4.5, 1300, 90),
('鱼香肉丝', '甜酸辣味炒肉丝', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Sichuan%20fish%20flavored%20pork%20shreds&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 290, "protein": 22, "fat": 18, "carbs": 15}', 4.3, 1100, 87),
('麻辣香锅', '干锅麻辣炒菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Sichuan%20spicy%20dry%20pot%20mixed%20vegetables&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 340, "protein": 18, "fat": 22, "carbs": 20}', 4.6, 950, 88);

-- 插入湘菜菜品 (150个)
INSERT INTO dishes (name, description, image_url, category_id, nutrition_facts, avg_rating, review_count, popularity_score) VALUES
('剁椒鱼头', '湖南经典蒸鱼头', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Hunan%20steamed%20fish%20head%20with%20chopped%20peppers&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 260, "protein": 30, "fat": 12, "carbs": 8}', 4.7, 1400, 93),
('口味虾', '麻辣小龙虾', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Hunan%20spicy%20crayfish%20with%20garlic&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 180, "protein": 20, "fat": 8, "carbs": 6}', 4.8, 2000, 96),
('臭豆腐', '长沙特色小吃', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Changsha%20stinky%20tofu%20street%20snack&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 220, "protein": 12, "fat": 15, "carbs": 12}', 4.2, 800, 75),
('糖醋排骨', '酸甜可口的排骨', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Hunan%20sweet%20and%20sour%20pork%20ribs&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 420, "protein": 28, "fat": 25, "carbs": 25}', 4.5, 1200, 89),
('辣椒炒肉', '湖南家常菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Hunan%20stir%20fried%20pork%20with%20peppers&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 280, "protein": 24, "fat": 18, "carbs": 10}', 4.4, 950, 85),
('毛氏红烧肉', '湖南特色红烧肉', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Hunan%20Mao%20style%20braised%20pork%20belly&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 480, "protein": 22, "fat": 38, "carbs": 15}', 4.6, 1100, 88),
('湘西腊肉', '烟熏腊肉片', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Xiangxi%20smoked%20bacon%20slices&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 350, "protein": 25, "fat": 26, "carbs": 5}', 4.3, 700, 78),
('血鸭', '湖南传统鸭肉菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Hunan%20blood%20duck%20traditional%20dish&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 320, "protein": 28, "fat": 20, "carbs": 8}', 4.2, 600, 72),
('湖南米粉', '长沙特色米粉', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Changsha%20rice%20noodles%20with%20toppings&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 380, "protein": 15, "fat": 12, "carbs": 55}', 4.4, 1300, 86),
('酸辣粉', '重庆酸辣粉丝', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Chongqing%20hot%20and%20sour%20noodles&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 320, "protein": 8, "fat": 10, "carbs": 50}', 4.3, 900, 82);

-- 插入粤菜菜品 (100个)
INSERT INTO dishes (name, description, image_url, category_id, nutrition_facts, avg_rating, review_count, popularity_score) VALUES
('白切鸡', '广东经典白切鸡', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Cantonese%20white%20cut%20chicken%20with%20ginger%20sauce&image_size=square', (SELECT id FROM categories WHERE name = '粤菜' LIMIT 1), '{"calories": 200, "protein": 30, "fat": 8, "carbs": 2}', 4.5, 1100, 88),
('烧鹅', '广式烧鹅', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Cantonese%20roasted%20goose%20crispy%20skin&image_size=square', (SELECT id FROM categories WHERE name = '粤菜' LIMIT 1), '{"calories": 380, "protein": 25, "fat": 28, "carbs": 5}', 4.7, 1500, 92),
('叉烧包', '广式茶点叉烧包', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Cantonese%20char%20siu%20bao%20steamed%20buns&image_size=square', (SELECT id FROM categories WHERE name = '粤菜' LIMIT 1), '{"calories": 280, "protein": 12, "fat": 8, "carbs": 42}', 4.6, 1800, 94),
('虾饺', '广式茶点虾饺', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Cantonese%20har%20gow%20shrimp%20dumplings&image_size=square', (SELECT id FROM categories WHERE name = '粤菜' LIMIT 1), '{"calories": 180, "protein": 15, "fat": 6, "carbs": 20}', 4.8, 2200, 96),
('烧卖', '广式烧卖', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Cantonese%20siu%20mai%20pork%20dumplings&image_size=square', (SELECT id FROM categories WHERE name = '粤菜' LIMIT 1), '{"calories": 220, "protein": 12, "fat": 10, "carbs": 22}', 4.5, 1600, 90),
('蒸排骨', '豉汁蒸排骨', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Cantonese%20steamed%20pork%20ribs%20with%20black%20bean&image_size=square', (SELECT id FROM categories WHERE name = '粤菜' LIMIT 1), '{"calories": 320, "protein": 25, "fat": 22, "carbs": 8}', 4.4, 1200, 87),
('白灼虾', '白灼基围虾', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Cantonese%20blanched%20shrimp%20with%20soy%20sauce&image_size=square', (SELECT id FROM categories WHERE name = '粤菜' LIMIT 1), '{"calories": 120, "protein": 24, "fat": 2, "carbs": 2}', 4.6, 1400, 89),
('糖醋咕噜肉', '广式糖醋肉', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Cantonese%20sweet%20and%20sour%20pork%20with%20pineapple&image_size=square', (SELECT id FROM categories WHERE name = '粤菜' LIMIT 1), '{"calories": 420, "protein": 20, "fat": 18, "carbs": 48}', 4.3, 1000, 84),
('白切鸭', '广式白切鸭', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Cantonese%20white%20cut%20duck%20with%20plum%20sauce&image_size=square', (SELECT id FROM categories WHERE name = '粤菜' LIMIT 1), '{"calories": 280, "protein": 28, "fat": 16, "carbs": 3}', 4.4, 900, 82),
('艇仔粥', '广式海鲜粥', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Cantonese%20boat%20congee%20with%20seafood&image_size=square', (SELECT id FROM categories WHERE name = '粤菜' LIMIT 1), '{"calories": 250, "protein": 18, "fat": 8, "carbs": 32}', 4.5, 1100, 86);

-- 插入海南特色菜品 (100个)
INSERT INTO dishes (name, description, image_url, category_id, nutrition_facts, avg_rating, review_count, popularity_score) VALUES
('海南鸡饭', '海南特色白切鸡配香米饭', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Hainan%20chicken%20rice%20with%20fragrant%20rice&image_size=square', (SELECT id FROM categories WHERE name = '海南菜' LIMIT 1), '{"calories": 450, "protein": 35, "fat": 15, "carbs": 45}', 4.8, 2500, 98),
('文昌鸡', '海南文昌特产鸡', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Hainan%20Wenchang%20chicken%20specialty&image_size=square', (SELECT id FROM categories WHERE name = '海南菜' LIMIT 1), '{"calories": 280, "protein": 32, "fat": 14, "carbs": 5}', 4.7, 1800, 94),
('加积鸭', '海南加积特产鸭', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Hainan%20Jiaji%20duck%20specialty&image_size=square', (SELECT id FROM categories WHERE name = '海南菜' LIMIT 1), '{"calories": 320, "protein": 28, "fat": 20, "carbs": 6}', 4.6, 1200, 89),
('东山羊', '海南东山特产羊肉', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Hainan%20Dongshan%20goat%20meat%20specialty&image_size=square', (SELECT id FROM categories WHERE name = '海南菜' LIMIT 1), '{"calories": 350, "protein": 30, "fat": 22, "carbs": 8}', 4.5, 1000, 86),
('和乐蟹', '海南和乐特产螃蟹', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Hainan%20Hele%20crab%20specialty&image_size=square', (SELECT id FROM categories WHERE name = '海南菜' LIMIT 1), '{"calories": 180, "protein": 20, "fat": 8, "carbs": 5}', 4.7, 1500, 91),
('椰子饭', '椰子壳蒸糯米饭', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Hainan%20coconut%20rice%20in%20coconut%20shell&image_size=square', (SELECT id FROM categories WHERE name = '海南菜' LIMIT 1), '{"calories": 380, "protein": 8, "fat": 12, "carbs": 62}', 4.4, 900, 83),
('清补凉', '海南特色甜品', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Hainan%20qingbuliang%20dessert%20soup&image_size=square', (SELECT id FROM categories WHERE name = '海南菜' LIMIT 1), '{"calories": 220, "protein": 6, "fat": 3, "carbs": 48}', 4.6, 1600, 88),
('海南粉', '海南特色米粉', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Hainan%20rice%20noodles%20with%20toppings&image_size=square', (SELECT id FROM categories WHERE name = '海南菜' LIMIT 1), '{"calories": 350, "protein": 12, "fat": 8, "carbs": 58}', 4.3, 1100, 85),
('抱罗粉', '海南抱罗特色粉', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Hainan%20Baoluo%20noodles%20specialty&image_size=square', (SELECT id FROM categories WHERE name = '海南菜' LIMIT 1), '{"calories": 320, "protein": 10, "fat": 6, "carbs": 60}', 4.2, 800, 78),
('陵水酸粉', '海南陵水酸辣粉', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Hainan%20Lingshui%20sour%20noodles&image_size=square', (SELECT id FROM categories WHERE name = '海南菜' LIMIT 1), '{"calories": 280, "protein": 8, "fat": 5, "carbs": 55}', 4.4, 1000, 82);

-- 插入外卖热门菜品 (150个)
INSERT INTO dishes (name, description, image_url, category_id, nutrition_facts, avg_rating, review_count, popularity_score) VALUES
('黄焖鸡米饭', '外卖热门黄焖鸡', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=braised%20chicken%20rice%20takeaway%20meal&image_size=square', (SELECT id FROM categories WHERE name = '外卖' LIMIT 1), '{"calories": 520, "protein": 28, "fat": 18, "carbs": 65}', 4.3, 3000, 92),
('兰州拉面', '正宗兰州牛肉面', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Lanzhou%20beef%20noodles%20authentic&image_size=square', (SELECT id FROM categories WHERE name = '外卖' LIMIT 1), '{"calories": 480, "protein": 22, "fat": 15, "carbs": 68}', 4.5, 2800, 89),
('沙县小吃', '沙县特色混沌', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Shaxian%20snacks%20wonton%20soup&image_size=square', (SELECT id FROM categories WHERE name = '外卖' LIMIT 1), '{"calories": 380, "protein": 15, "fat": 12, "carbs": 52}', 4.2, 2200, 85),
('麻辣烫', '四川麻辣烫', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Sichuan%20malatang%20spicy%20hot%20pot&image_size=square', (SELECT id FROM categories WHERE name = '外卖' LIMIT 1), '{"calories": 420, "protein": 18, "fat": 20, "carbs": 45}', 4.4, 2500, 88),
('煲仔饭', '广式煲仔饭', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Cantonese%20clay%20pot%20rice%20with%20sausage&image_size=square', (SELECT id FROM categories WHERE name = '外卖' LIMIT 1), '{"calories": 550, "protein": 25, "fat": 22, "carbs": 68}', 4.6, 1800, 90),
('重庆小面', '重庆特色小面', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Chongqing%20small%20noodles%20spicy&image_size=square', (SELECT id FROM categories WHERE name = '外卖' LIMIT 1), '{"calories": 450, "protein": 16, "fat": 18, "carbs": 62}', 4.5, 2000, 87),
('过桥米线', '云南过桥米线', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Yunnan%20crossing%20bridge%20rice%20noodles&image_size=square', (SELECT id FROM categories WHERE name = '外卖' LIMIT 1), '{"calories": 420, "protein": 20, "fat": 12, "carbs": 65}', 4.4, 1600, 86),
('螺蛳粉', '广西柳州螺蛳粉', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Guangxi%20Liuzhou%20snail%20noodles&image_size=square', (SELECT id FROM categories WHERE name = '外卖' LIMIT 1), '{"calories": 380, "protein": 14, "fat": 15, "carbs": 52}', 4.3, 1900, 84),
('烤肉拌饭', '韩式烤肉拌饭', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Korean%20BBQ%20rice%20bowl&image_size=square', (SELECT id FROM categories WHERE name = '外卖' LIMIT 1), '{"calories": 580, "protein": 30, "fat": 25, "carbs": 58}', 4.5, 1700, 88),
('日式拉面', '日式豚骨拉面', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Japanese%20tonkotsu%20ramen%20noodles&image_size=square', (SELECT id FROM categories WHERE name = '外卖' LIMIT 1), '{"calories": 520, "protein": 24, "fat": 22, "carbs": 58}', 4.6, 1500, 89);

-- 插入校园食堂菜品 (150个)
INSERT INTO dishes (name, description, image_url, category_id, nutrition_facts, avg_rating, review_count, popularity_score) VALUES
('红烧肉', '食堂经典红烧肉', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=cafeteria%20braised%20pork%20belly%20classic&image_size=square', (SELECT id FROM categories WHERE name = '食堂' LIMIT 1), '{"calories": 420, "protein": 22, "fat": 32, "carbs": 12}', 4.2, 1500, 85),
('糖醋里脊', '食堂糖醋里脊', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=cafeteria%20sweet%20sour%20pork%20tenderloin&image_size=square', (SELECT id FROM categories WHERE name = '食堂' LIMIT 1), '{"calories": 380, "protein": 25, "fat": 18, "carbs": 28}', 4.1, 1200, 82),
('宫保鸡丁', '食堂宫保鸡丁', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=cafeteria%20kung%20pao%20chicken%20diced&image_size=square', (SELECT id FROM categories WHERE name = '食堂' LIMIT 1), '{"calories": 320, "protein": 28, "fat": 18, "carbs": 15}', 4.0, 1800, 88),
('土豆丝', '食堂炒土豆丝', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=cafeteria%20stir%20fried%20potato%20shreds&image_size=square', (SELECT id FROM categories WHERE name = '食堂' LIMIT 1), '{"calories": 180, "protein": 4, "fat": 8, "carbs": 28}', 3.9, 2000, 75),
('青椒肉丝', '食堂青椒肉丝', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=cafeteria%20green%20pepper%20pork%20shreds&image_size=square', (SELECT id FROM categories WHERE name = '食堂' LIMIT 1), '{"calories": 280, "protein": 22, "fat": 16, "carbs": 12}', 4.1, 1600, 83),
('西红柿鸡蛋', '食堂西红柿炒鸡蛋', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=cafeteria%20tomato%20scrambled%20eggs&image_size=square', (SELECT id FROM categories WHERE name = '食堂' LIMIT 1), '{"calories": 220, "protein": 12, "fat": 15, "carbs": 12}', 4.0, 2200, 80),
('麻婆豆腐', '食堂麻婆豆腐', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=cafeteria%20mapo%20tofu%20spicy&image_size=square', (SELECT id FROM categories WHERE name = '食堂' LIMIT 1), '{"calories": 250, "protein": 15, "fat": 18, "carbs": 12}', 4.2, 1400, 84),
('白米饭', '食堂白米饭', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=cafeteria%20steamed%20white%20rice&image_size=square', (SELECT id FROM categories WHERE name = '食堂' LIMIT 1), '{"calories": 180, "protein": 4, "fat": 1, "carbs": 40}', 3.8, 3000, 70),
('紫菜蛋花汤', '食堂紫菜蛋花汤', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=cafeteria%20seaweed%20egg%20drop%20soup&image_size=square', (SELECT id FROM categories WHERE name = '食堂' LIMIT 1), '{"calories": 80, "protein": 6, "fat": 4, "carbs": 6}', 3.9, 1800, 72),
('小白菜', '食堂清炒小白菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=cafeteria%20stir%20fried%20baby%20bok%20choy&image_size=square', (SELECT id FROM categories WHERE name = '食堂' LIMIT 1), '{"calories": 60, "protein": 3, "fat": 3, "carbs": 8}', 3.7, 1500, 68);

-- 插入减脂健康菜品 (100个)
INSERT INTO dishes (name, description, image_url, category_id, nutrition_facts, avg_rating, review_count, popularity_score) VALUES
('蒸蛋羹', '低脂高蛋白蒸蛋', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=steamed%20egg%20custard%20healthy%20low%20fat&image_size=square', (SELECT id FROM categories WHERE name = '减脂餐' LIMIT 1), '{"calories": 120, "protein": 12, "fat": 6, "carbs": 4}', 4.3, 800, 78),
('水煮蛋', '纯天然水煮鸡蛋', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=boiled%20eggs%20natural%20protein&image_size=square', (SELECT id FROM categories WHERE name = '减脂餐' LIMIT 1), '{"calories": 80, "protein": 7, "fat": 5, "carbs": 1}', 4.1, 1200, 75),
('蒸鸡胸肉', '低脂高蛋白鸡胸肉', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=steamed%20chicken%20breast%20low%20fat%20protein&image_size=square', (SELECT id FROM categories WHERE name = '减脂餐' LIMIT 1), '{"calories": 140, "protein": 26, "fat": 3, "carbs": 0}', 4.4, 900, 82),
('水煮西兰花', '清淡水煮西兰花', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=boiled%20broccoli%20light%20healthy&image_size=square', (SELECT id FROM categories WHERE name = '减脂餐' LIMIT 1), '{"calories": 35, "protein": 3, "fat": 0, "carbs": 7}', 4.0, 600, 70),
('蒸南瓜', '天然甜味蒸南瓜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=steamed%20pumpkin%20natural%20sweet&image_size=square', (SELECT id FROM categories WHERE name = '减脂餐' LIMIT 1), '{"calories": 50, "protein": 2, "fat": 0, "carbs": 12}', 4.2, 700, 73),
('清蒸鱼', '低脂清蒸鲈鱼', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=steamed%20bass%20fish%20low%20fat&image_size=square', (SELECT id FROM categories WHERE name = '减脂餐' LIMIT 1), '{"calories": 130, "protein": 24, "fat": 3, "carbs": 0}', 4.5, 1000, 85),
('水煮虾', '原味水煮虾仁', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=boiled%20shrimp%20natural%20flavor&image_size=square', (SELECT id FROM categories WHERE name = '减脂餐' LIMIT 1), '{"calories": 100, "protein": 20, "fat": 1, "carbs": 1}', 4.4, 850, 80),
('蒸蛋白', '纯蛋白蒸制', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=steamed%20egg%20whites%20pure%20protein&image_size=square', (SELECT id FROM categories WHERE name = '减脂餐' LIMIT 1), '{"calories": 60, "protein": 12, "fat": 0, "carbs": 1}', 4.2, 500, 72),
('水煮菠菜', '清淡水煮菠菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=boiled%20spinach%20light%20healthy&image_size=square', (SELECT id FROM categories WHERE name = '减脂餐' LIMIT 1), '{"calories": 25, "protein": 3, "fat": 0, "carbs": 4}', 3.9, 400, 68),
('蒸豆腐', '嫩滑蒸豆腐', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=steamed%20tofu%20silky%20smooth&image_size=square', (SELECT id FROM categories WHERE name = '减脂餐' LIMIT 1), '{"calories": 90, "protein": 10, "fat": 5, "carbs": 3}', 4.1, 650, 74);