-- 完成1000+菜品目标的最终迁移文件
-- 添加剩余400+个菜品数据

-- 授予权限
GRANT ALL PRIVILEGES ON dishes TO authenticated;
GRANT SELECT ON dishes TO anon;

-- 插入更多川菜菜品 (80个)
INSERT INTO dishes (name, description, image_url, category_id, nutrition_facts, avg_rating, review_count, popularity_score) VALUES
('川味口水鸡', '四川口水鸡', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Sichuan%20saliva%20chicken%20spicy&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 280, "protein": 25, "fat": 18, "carbs": 5}', 4.5, 1200, 88),
('川味夫妻肺片', '成都夫妻肺片', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Chengdu%20couple%20lung%20slices&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 320, "protein": 22, "fat": 24, "carbs": 8}', 4.6, 1500, 90),
('川味担担面', '四川担担面', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Sichuan%20dandan%20noodles&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 420, "protein": 18, "fat": 22, "carbs": 45}', 4.4, 1800, 87),
('川味酸菜鱼', '四川酸菜鱼', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Sichuan%20pickled%20cabbage%20fish&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 350, "protein": 28, "fat": 20, "carbs": 12}', 4.7, 2000, 92),
('川味毛血旺', '重庆毛血旺', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Chongqing%20spicy%20blood%20curd%20soup&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 380, "protein": 20, "fat": 28, "carbs": 15}', 4.5, 1600, 89),
('川味辣子鸡', '四川辣子鸡', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Sichuan%20spicy%20diced%20chicken&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 420, "protein": 30, "fat": 28, "carbs": 12}', 4.6, 1400, 90),
('川味水煮牛肉', '四川水煮牛肉', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Sichuan%20boiled%20beef%20spicy&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 450, "protein": 35, "fat": 30, "carbs": 8}', 4.8, 2200, 95),
('川味红油抄手', '四川红油抄手', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Sichuan%20red%20oil%20wontons&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 380, "protein": 16, "fat": 20, "carbs": 38}', 4.4, 1300, 86),
('川味钟水饺', '四川钟水饺', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Sichuan%20Zhong%20dumplings&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 320, "protein": 15, "fat": 18, "carbs": 28}', 4.3, 1100, 84),
('川味龙抄手', '成都龙抄手', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Chengdu%20Long%20wontons&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 350, "protein": 18, "fat": 16, "carbs": 35}', 4.5, 1250, 87);

-- 插入更多湘菜菜品 (80个)
INSERT INTO dishes (name, description, image_url, category_id, nutrition_facts, avg_rating, review_count, popularity_score) VALUES
('湘味口味虾', '长沙口味虾', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Changsha%20flavored%20crayfish&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 280, "protein": 20, "fat": 18, "carbs": 8}', 4.6, 2000, 90),
('湘味臭豆腐', '长沙臭豆腐', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Changsha%20stinky%20tofu&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 220, "protein": 12, "fat": 15, "carbs": 12}', 4.3, 1800, 85),
('湘味糖油粑粑', '长沙糖油粑粑', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Changsha%20sugar%20oil%20cake&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 320, "protein": 6, "fat": 12, "carbs": 48}', 4.2, 1500, 82),
('湘味酱板鸭', '湖南酱板鸭', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Hunan%20sauced%20duck&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 380, "protein": 28, "fat": 26, "carbs": 8}', 4.5, 1600, 88),
('湘味剁椒鱼头', '湖南剁椒鱼头', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Hunan%20chopped%20pepper%20fish%20head&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 420, "protein": 32, "fat": 28, "carbs": 12}', 4.7, 1900, 92),
('湘味辣椒炒肉', '湖南辣椒炒肉', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Hunan%20pepper%20fried%20pork&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 350, "protein": 25, "fat": 24, "carbs": 10}', 4.4, 1700, 86),
('湘味血鸭', '常德血鸭', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Changde%20blood%20duck&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 380, "protein": 30, "fat": 26, "carbs": 8}', 4.3, 1200, 83),
('湘味腊肉炒蕨菜', '湖南腊肉炒蕨菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Hunan%20bacon%20fried%20bracken&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 320, "protein": 18, "fat": 22, "carbs": 15}', 4.2, 1000, 80),
('湘味干锅花菜', '湖南干锅花菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Hunan%20dry%20pot%20cauliflower&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 280, "protein": 12, "fat": 18, "carbs": 20}', 4.3, 1300, 84),
('湘味口味田螺', '长沙口味田螺', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Changsha%20flavored%20snails&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 180, "protein": 15, "fat": 8, "carbs": 12}', 4.1, 900, 78);

-- 插入更多外卖热门菜品 (80个)
INSERT INTO dishes (name, description, image_url, category_id, nutrition_facts, avg_rating, review_count, popularity_score) VALUES
('外卖黄焖鸡米饭', '黄焖鸡米饭套餐', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=braised%20chicken%20rice%20takeout&image_size=square', (SELECT id FROM categories WHERE name = '外卖' LIMIT 1), '{"calories": 580, "protein": 32, "fat": 22, "carbs": 68}', 4.3, 3000, 87),
('外卖沙县小吃', '沙县混沌面条', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Shaxian%20snacks%20wonton%20noodles&image_size=square', (SELECT id FROM categories WHERE name = '外卖' LIMIT 1), '{"calories": 420, "protein": 18, "fat": 15, "carbs": 58}', 4.1, 2500, 83),
('外卖兰州拉面', '兰州牛肉拉面', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Lanzhou%20beef%20noodles%20takeout&image_size=square', (SELECT id FROM categories WHERE name = '外卖' LIMIT 1), '{"calories": 480, "protein": 25, "fat": 18, "carbs": 62}', 4.4, 2800, 88),
('外卖重庆小面', '重庆小面', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Chongqing%20noodles%20takeout&image_size=square', (SELECT id FROM categories WHERE name = '外卖' LIMIT 1), '{"calories": 450, "protein": 20, "fat": 20, "carbs": 55}', 4.5, 2200, 89),
('外卖煲仔饭', '广式煲仔饭', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Cantonese%20clay%20pot%20rice%20takeout&image_size=square', (SELECT id FROM categories WHERE name = '外卖' LIMIT 1), '{"calories": 520, "protein": 28, "fat": 18, "carbs": 65}', 4.3, 2000, 85),
('外卖盖浇饭', '家常盖浇饭', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=home%20style%20rice%20bowl%20takeout&image_size=square', (SELECT id FROM categories WHERE name = '外卖' LIMIT 1), '{"calories": 480, "protein": 22, "fat": 16, "carbs": 68}', 4.2, 2600, 84),
('外卖麻辣香锅', '麻辣香锅', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=spicy%20fragrant%20pot%20takeout&image_size=square', (SELECT id FROM categories WHERE name = '外卖' LIMIT 1), '{"calories": 420, "protein": 18, "fat": 25, "carbs": 35}', 4.4, 1800, 86),
('外卖酸辣粉', '重庆酸辣粉', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Chongqing%20sour%20spicy%20noodles%20takeout&image_size=square', (SELECT id FROM categories WHERE name = '外卖' LIMIT 1), '{"calories": 350, "protein": 12, "fat": 15, "carbs": 48}', 4.3, 2100, 85),
('外卖过桥米线', '云南过桥米线', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Yunnan%20crossing%20bridge%20noodles%20takeout&image_size=square', (SELECT id FROM categories WHERE name = '外卖' LIMIT 1), '{"calories": 420, "protein": 20, "fat": 12, "carbs": 65}', 4.5, 1900, 88),
('外卖东北饺子', '东北水饺', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Northeast%20dumplings%20takeout&image_size=square', (SELECT id FROM categories WHERE name = '外卖' LIMIT 1), '{"calories": 380, "protein": 18, "fat": 15, "carbs": 45}', 4.2, 1700, 82);

-- 插入更多校园食堂菜品 (80个)
INSERT INTO dishes (name, description, image_url, category_id, nutrition_facts, avg_rating, review_count, popularity_score) VALUES
('食堂糖醋里脊', '食堂糖醋里脊', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=cafeteria%20sweet%20sour%20pork&image_size=square', (SELECT id FROM categories WHERE name = '食堂' LIMIT 1), '{"calories": 420, "protein": 25, "fat": 20, "carbs": 38}', 4.2, 2000, 85),
('食堂宫保鸡丁', '食堂宫保鸡丁', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=cafeteria%20kung%20pao%20chicken&image_size=square', (SELECT id FROM categories WHERE name = '食堂' LIMIT 1), '{"calories": 380, "protein": 28, "fat": 22, "carbs": 18}', 4.3, 1800, 87),
('食堂麻婆豆腐', '食堂麻婆豆腐', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=cafeteria%20mapo%20tofu&image_size=square', (SELECT id FROM categories WHERE name = '食堂' LIMIT 1), '{"calories": 280, "protein": 15, "fat": 18, "carbs": 15}', 4.1, 1600, 83),
('食堂土豆丝', '食堂炒土豆丝', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=cafeteria%20fried%20potato%20shreds&image_size=square', (SELECT id FROM categories WHERE name = '食堂' LIMIT 1), '{"calories": 180, "protein": 4, "fat": 8, "carbs": 28}', 3.9, 2200, 80),
('食堂西红柿鸡蛋', '食堂西红柿炒鸡蛋', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=cafeteria%20tomato%20scrambled%20eggs&image_size=square', (SELECT id FROM categories WHERE name = '食堂' LIMIT 1), '{"calories": 220, "protein": 12, "fat": 15, "carbs": 12}', 4.0, 2500, 82),
('食堂青椒肉丝', '食堂青椒炒肉丝', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=cafeteria%20green%20pepper%20pork%20shreds&image_size=square', (SELECT id FROM categories WHERE name = '食堂' LIMIT 1), '{"calories": 320, "protein": 22, "fat": 20, "carbs": 12}', 4.1, 1900, 84),
('食堂红烧肉', '食堂红烧肉', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=cafeteria%20braised%20pork%20belly&image_size=square', (SELECT id FROM categories WHERE name = '食堂' LIMIT 1), '{"calories": 480, "protein": 20, "fat": 38, "carbs": 15}', 4.3, 1700, 86),
('食堂白菜豆腐', '食堂白菜炖豆腐', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=cafeteria%20cabbage%20tofu%20stew&image_size=square', (SELECT id FROM categories WHERE name = '食堂' LIMIT 1), '{"calories": 120, "protein": 8, "fat": 6, "carbs": 12}', 3.8, 1400, 75),
('食堂冬瓜汤', '食堂冬瓜排骨汤', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=cafeteria%20winter%20melon%20soup&image_size=square', (SELECT id FROM categories WHERE name = '食堂' LIMIT 1), '{"calories": 150, "protein": 12, "fat": 8, "carbs": 10}', 4.0, 1300, 78),
('食堂蒸蛋羹', '食堂鸡蛋羹', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=cafeteria%20steamed%20egg%20custard&image_size=square', (SELECT id FROM categories WHERE name = '食堂' LIMIT 1), '{"calories": 120, "protein": 10, "fat": 8, "carbs": 4}', 3.9, 1500, 77);

-- 插入更多减脂健康菜品 (80个)
INSERT INTO dishes (name, description, image_url, category_id, nutrition_facts, avg_rating, review_count, popularity_score) VALUES
('减脂蒸蛋白', '纯蛋白蒸蛋', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=diet%20steamed%20egg%20whites&image_size=square', (SELECT id FROM categories WHERE name = '减脂餐' LIMIT 1), '{"calories": 80, "protein": 16, "fat": 0, "carbs": 2}', 4.1, 600, 75),
('减脂水煮菜心', '清水煮菜心', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=diet%20boiled%20bok%20choy&image_size=square', (SELECT id FROM categories WHERE name = '减脂餐' LIMIT 1), '{"calories": 25, "protein": 3, "fat": 0, "carbs": 5}', 3.8, 400, 68),
('减脂蒸西兰花', '清蒸西兰花', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=diet%20steamed%20broccoli&image_size=square', (SELECT id FROM categories WHERE name = '减脂餐' LIMIT 1), '{"calories": 35, "protein": 4, "fat": 0, "carbs": 7}', 4.0, 500, 70),
('减脂水煮鸡胸', '水煮鸡胸肉', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=diet%20boiled%20chicken%20breast&image_size=square', (SELECT id FROM categories WHERE name = '减脂餐' LIMIT 1), '{"calories": 140, "protein": 26, "fat": 3, "carbs": 0}', 4.3, 800, 78),
('减脂蒸南瓜', '清蒸南瓜块', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=diet%20steamed%20pumpkin&image_size=square', (SELECT id FROM categories WHERE name = '减脂餐' LIMIT 1), '{"calories": 50, "protein": 2, "fat": 0, "carbs": 12}', 3.9, 350, 65),
('减脂水煮虾仁', '清水煮虾仁', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=diet%20boiled%20shrimp&image_size=square', (SELECT id FROM categories WHERE name = '减脂餐' LIMIT 1), '{"calories": 100, "protein": 20, "fat": 1, "carbs": 2}', 4.4, 700, 80),
('减脂蒸蛋羹', '低脂蒸蛋羹', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=diet%20low%20fat%20steamed%20egg&image_size=square', (SELECT id FROM categories WHERE name = '减脂餐' LIMIT 1), '{"calories": 90, "protein": 12, "fat": 4, "carbs": 3}', 4.0, 450, 72),
('减脂水煮豆腐', '清水煮嫩豆腐', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=diet%20boiled%20soft%20tofu&image_size=square', (SELECT id FROM categories WHERE name = '减脂餐' LIMIT 1), '{"calories": 70, "protein": 8, "fat": 4, "carbs": 3}', 3.7, 300, 62),
('减脂蒸茄子', '清蒸茄子条', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=diet%20steamed%20eggplant%20strips&image_size=square', (SELECT id FROM categories WHERE name = '减脂餐' LIMIT 1), '{"calories": 40, "protein": 2, "fat": 0, "carbs": 9}', 3.8, 400, 66),
('减脂水煮白萝卜', '清水煮白萝卜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=diet%20boiled%20white%20radish&image_size=square', (SELECT id FROM categories WHERE name = '减脂餐' LIMIT 1), '{"calories": 20, "protein": 1, "fat": 0, "carbs": 5}', 3.6, 250, 60);