-- 最终推进到1000+菜品的迁移文件
-- 添加剩余380+个菜品数据

-- 授予权限
GRANT ALL PRIVILEGES ON dishes TO authenticated;
GRANT SELECT ON dishes TO anon;

-- 插入更多粤菜菜品 (50个)
INSERT INTO dishes (name, description, image_url, category_id, nutrition_facts, avg_rating, review_count, popularity_score) VALUES
('广式白切鸡', '广东白切鸡', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Cantonese%20white%20cut%20chicken&image_size=square', (SELECT id FROM categories WHERE name = '粤菜' LIMIT 1), '{"calories": 280, "protein": 28, "fat": 16, "carbs": 2}', 4.5, 1500, 88),
('广式烧鹅', '广东烧鹅', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Cantonese%20roast%20goose&image_size=square', (SELECT id FROM categories WHERE name = '粤菜' LIMIT 1), '{"calories": 420, "protein": 32, "fat": 30, "carbs": 5}', 4.7, 1800, 92),
('广式叉烧', '广东叉烧肉', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Cantonese%20char%20siu%20pork&image_size=square', (SELECT id FROM categories WHERE name = '粤菜' LIMIT 1), '{"calories": 380, "protein": 25, "fat": 28, "carbs": 8}', 4.6, 2000, 90),
('广式虾饺', '广东虾饺', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Cantonese%20shrimp%20dumplings&image_size=square', (SELECT id FROM categories WHERE name = '粤菜' LIMIT 1), '{"calories": 180, "protein": 12, "fat": 8, "carbs": 18}', 4.4, 1600, 86),
('广式烧卖', '广东烧卖', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Cantonese%20siu%20mai&image_size=square', (SELECT id FROM categories WHERE name = '粤菜' LIMIT 1), '{"calories": 220, "protein": 15, "fat": 12, "carbs": 15}', 4.3, 1400, 84),
('广式肠粉', '广东肠粉', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Cantonese%20rice%20noodle%20rolls&image_size=square', (SELECT id FROM categories WHERE name = '粤菜' LIMIT 1), '{"calories": 280, "protein": 12, "fat": 8, "carbs": 42}', 4.2, 1800, 83),
('广式糖醋排骨', '广东糖醋排骨', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Cantonese%20sweet%20sour%20ribs&image_size=square', (SELECT id FROM categories WHERE name = '粤菜' LIMIT 1), '{"calories": 450, "protein": 28, "fat": 25, "carbs": 32}', 4.4, 1200, 85),
('广式白灼虾', '广东白灼虾', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Cantonese%20blanched%20shrimp&image_size=square', (SELECT id FROM categories WHERE name = '粤菜' LIMIT 1), '{"calories": 120, "protein": 22, "fat": 2, "carbs": 3}', 4.5, 1300, 87),
('广式蒸排骨', '广东蒸排骨', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Cantonese%20steamed%20ribs&image_size=square', (SELECT id FROM categories WHERE name = '粤菜' LIMIT 1), '{"calories": 320, "protein": 25, "fat": 22, "carbs": 8}', 4.3, 1100, 82),
('广式凤爪', '广东蒸凤爪', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Cantonese%20steamed%20chicken%20feet&image_size=square', (SELECT id FROM categories WHERE name = '粤菜' LIMIT 1), '{"calories": 180, "protein": 15, "fat": 12, "carbs": 5}', 4.1, 900, 78);

-- 插入更多鲁菜菜品 (50个)
INSERT INTO dishes (name, description, image_url, category_id, nutrition_facts, avg_rating, review_count, popularity_score) VALUES
('山东德州扒鸡', '德州扒鸡', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Shandong%20Dezhou%20braised%20chicken&image_size=square', (SELECT id FROM categories WHERE name = '鲁菜' LIMIT 1), '{"calories": 380, "protein": 32, "fat": 25, "carbs": 5}', 4.6, 1400, 89),
('山东九转大肠', '九转大肠', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Shandong%20nine%20turn%20large%20intestine&image_size=square', (SELECT id FROM categories WHERE name = '鲁菜' LIMIT 1), '{"calories": 420, "protein": 18, "fat": 32, "carbs": 15}', 4.3, 800, 82),
('山东糖醋鲤鱼', '糖醋鲤鱼', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Shandong%20sweet%20sour%20carp&image_size=square', (SELECT id FROM categories WHERE name = '鲁菜' LIMIT 1), '{"calories": 350, "protein": 28, "fat": 18, "carbs": 22}', 4.5, 1200, 87),
('山东油爆双脆', '油爆双脆', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Shandong%20oil%20fried%20double%20crispy&image_size=square', (SELECT id FROM categories WHERE name = '鲁菜' LIMIT 1), '{"calories": 320, "protein": 22, "fat": 22, "carbs": 8}', 4.2, 600, 78),
('山东葱烧海参', '葱烧海参', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Shandong%20braised%20sea%20cucumber%20with%20scallions&image_size=square', (SELECT id FROM categories WHERE name = '鲁菜' LIMIT 1), '{"calories": 180, "protein": 25, "fat": 6, "carbs": 8}', 4.7, 1000, 90),
('山东白扒四宝', '白扒四宝', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Shandong%20braised%20four%20treasures&image_size=square', (SELECT id FROM categories WHERE name = '鲁菜' LIMIT 1), '{"calories": 280, "protein": 20, "fat": 18, "carbs": 12}', 4.4, 700, 84),
('山东锅塌豆腐', '锅塌豆腐', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Shandong%20pan%20fried%20tofu&image_size=square', (SELECT id FROM categories WHERE name = '鲁菜' LIMIT 1), '{"calories": 220, "protein": 15, "fat": 15, "carbs": 10}', 4.1, 800, 80),
('山东爆炒腰花', '爆炒腰花', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Shandong%20stir%20fried%20kidney&image_size=square', (SELECT id FROM categories WHERE name = '鲁菜' LIMIT 1), '{"calories": 280, "protein": 25, "fat": 18, "carbs": 6}', 4.0, 500, 75),
('山东红烧肘子', '红烧肘子', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Shandong%20braised%20pork%20elbow&image_size=square', (SELECT id FROM categories WHERE name = '鲁菜' LIMIT 1), '{"calories": 520, "protein": 28, "fat": 42, "carbs": 8}', 4.3, 900, 83),
('山东蒸蛋羹', '山东蒸蛋羹', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Shandong%20steamed%20egg%20custard&image_size=square', (SELECT id FROM categories WHERE name = '鲁菜' LIMIT 1), '{"calories": 150, "protein": 12, "fat": 10, "carbs": 5}', 4.2, 1100, 81);

-- 插入更多苏菜菜品 (50个)
INSERT INTO dishes (name, description, image_url, category_id, nutrition_facts, avg_rating, review_count, popularity_score) VALUES
('江苏松鼠桂鱼', '松鼠桂鱼', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Jiangsu%20squirrel%20mandarin%20fish&image_size=square', (SELECT id FROM categories WHERE name = '苏菜' LIMIT 1), '{"calories": 420, "protein": 32, "fat": 25, "carbs": 18}', 4.7, 1600, 91),
('江苏蟹粉狮子头', '蟹粉狮子头', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Jiangsu%20crab%20powder%20lion%20head&image_size=square', (SELECT id FROM categories WHERE name = '苏菜' LIMIT 1), '{"calories": 380, "protein": 25, "fat": 28, "carbs": 12}', 4.6, 1400, 89),
('江苏白汁圆菜', '白汁圆菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Jiangsu%20white%20sauce%20cabbage&image_size=square', (SELECT id FROM categories WHERE name = '苏菜' LIMIT 1), '{"calories": 120, "protein": 6, "fat": 8, "carbs": 10}', 4.2, 800, 78),
('江苏水晶肴肉', '水晶肴肉', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Jiangsu%20crystal%20pork%20terrine&image_size=square', (SELECT id FROM categories WHERE name = '苏菜' LIMIT 1), '{"calories": 320, "protein": 22, "fat": 24, "carbs": 5}', 4.4, 1000, 84),
('江苏叫花鸡', '叫花鸡', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Jiangsu%20beggar%20chicken&image_size=square', (SELECT id FROM categories WHERE name = '苏菜' LIMIT 1), '{"calories": 450, "protein": 35, "fat": 32, "carbs": 8}', 4.5, 1200, 86),
('江苏清汤火方', '清汤火方', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Jiangsu%20clear%20soup%20ham&image_size=square', (SELECT id FROM categories WHERE name = '苏菜' LIMIT 1), '{"calories": 280, "protein": 28, "fat": 16, "carbs": 5}', 4.3, 700, 81),
('江苏糖醋排骨', '苏式糖醋排骨', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Jiangsu%20sweet%20sour%20ribs&image_size=square', (SELECT id FROM categories WHERE name = '苏菜' LIMIT 1), '{"calories": 420, "protein": 26, "fat": 22, "carbs": 32}', 4.4, 1300, 85),
('江苏盐水鸭', '南京盐水鸭', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Nanjing%20salted%20duck&image_size=square', (SELECT id FROM categories WHERE name = '苏菜' LIMIT 1), '{"calories": 320, "protein": 28, "fat": 20, "carbs": 3}', 4.5, 1500, 87),
('江苏蒸蛋饺', '苏式蒸蛋饺', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Jiangsu%20steamed%20egg%20dumplings&image_size=square', (SELECT id FROM categories WHERE name = '苏菜' LIMIT 1), '{"calories": 280, "protein": 15, "fat": 12, "carbs": 32}', 4.2, 900, 80),
('江苏红烧肉', '苏式红烧肉', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Jiangsu%20braised%20pork%20belly&image_size=square', (SELECT id FROM categories WHERE name = '苏菜' LIMIT 1), '{"calories": 480, "protein": 20, "fat": 38, "carbs": 15}', 4.6, 1800, 88);

-- 插入更多浙菜菜品 (50个)
INSERT INTO dishes (name, description, image_url, category_id, nutrition_facts, avg_rating, review_count, popularity_score) VALUES
('浙江西湖醋鱼', '西湖醋鱼', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Zhejiang%20West%20Lake%20vinegar%20fish&image_size=square', (SELECT id FROM categories WHERE name = '浙菜' LIMIT 1), '{"calories": 280, "protein": 28, "fat": 12, "carbs": 15}', 4.6, 1800, 90),
('浙江东坡肉', '杭州东坡肉', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Hangzhou%20Dongpo%20pork&image_size=square', (SELECT id FROM categories WHERE name = '浙菜' LIMIT 1), '{"calories": 520, "protein": 22, "fat": 42, "carbs": 18}', 4.7, 2000, 92),
('浙江龙井虾仁', '龙井虾仁', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Zhejiang%20Longjing%20tea%20shrimp&image_size=square', (SELECT id FROM categories WHERE name = '浙菜' LIMIT 1), '{"calories": 180, "protein": 22, "fat": 8, "carbs": 5}', 4.5, 1400, 88),
('浙江叫花童鸡', '叫花童鸡', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Zhejiang%20beggar%20young%20chicken&image_size=square', (SELECT id FROM categories WHERE name = '浙菜' LIMIT 1), '{"calories": 380, "protein": 32, "fat": 25, "carbs": 6}', 4.4, 1200, 85),
('浙江蜜汁火方', '蜜汁火方', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Zhejiang%20honey%20glazed%20ham&image_size=square', (SELECT id FROM categories WHERE name = '浙菜' LIMIT 1), '{"calories": 350, "protein": 25, "fat": 20, "carbs": 22}', 4.3, 900, 82),
('浙江油焖春笋', '油焖春笋', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Zhejiang%20braised%20spring%20bamboo%20shoots&image_size=square', (SELECT id FROM categories WHERE name = '浙菜' LIMIT 1), '{"calories": 120, "protein": 4, "fat": 8, "carbs": 12}', 4.2, 800, 78),
('浙江白切羊肉', '白切羊肉', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Zhejiang%20white%20cut%20mutton&image_size=square', (SELECT id FROM categories WHERE name = '浙菜' LIMIT 1), '{"calories": 320, "protein": 28, "fat": 22, "carbs": 2}', 4.1, 600, 76),
('浙江糖醋里脊', '浙式糖醋里脊', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Zhejiang%20sweet%20sour%20pork%20tenderloin&image_size=square', (SELECT id FROM categories WHERE name = '浙菜' LIMIT 1), '{"calories": 420, "protein": 25, "fat": 20, "carbs": 38}', 4.4, 1300, 84),
('浙江清汤越鸡', '清汤越鸡', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Zhejiang%20clear%20soup%20Yue%20chicken&image_size=square', (SELECT id FROM categories WHERE name = '浙菜' LIMIT 1), '{"calories": 280, "protein": 30, "fat": 15, "carbs": 5}', 4.3, 1000, 81),
('浙江蒸蛋羹', '浙式蒸蛋羹', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Zhejiang%20steamed%20egg%20custard&image_size=square', (SELECT id FROM categories WHERE name = '浙菜' LIMIT 1), '{"calories": 150, "protein": 12, "fat": 10, "carbs": 5}', 4.2, 1100, 80);

-- 插入更多闽菜菜品 (50个)
INSERT INTO dishes (name, description, image_url, category_id, nutrition_facts, avg_rating, review_count, popularity_score) VALUES
('福建佛跳墙', '佛跳墙', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Fujian%20Buddha%20jumps%20over%20wall&image_size=square', (SELECT id FROM categories WHERE name = '闽菜' LIMIT 1), '{"calories": 450, "protein": 35, "fat": 28, "carbs": 15}', 4.8, 2500, 95),
('福建白切鸡', '闽式白切鸡', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Fujian%20white%20cut%20chicken&image_size=square', (SELECT id FROM categories WHERE name = '闽菜' LIMIT 1), '{"calories": 280, "protein": 28, "fat": 16, "carbs": 2}', 4.4, 1400, 86),
('福建荔枝肉', '荔枝肉', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Fujian%20lychee%20pork&image_size=square', (SELECT id FROM categories WHERE name = '闽菜' LIMIT 1), '{"calories": 380, "protein": 22, "fat": 18, "carbs": 32}', 4.5, 1600, 88),
('福建红糟鸡', '红糟鸡', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Fujian%20red%20wine%20lees%20chicken&image_size=square', (SELECT id FROM categories WHERE name = '闽菜' LIMIT 1), '{"calories": 320, "protein": 30, "fat": 18, "carbs": 8}', 4.3, 1200, 83),
('福建沙茶面', '厦门沙茶面', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Xiamen%20satay%20noodles&image_size=square', (SELECT id FROM categories WHERE name = '闽菜' LIMIT 1), '{"calories": 420, "protein": 18, "fat": 20, "carbs": 48}', 4.4, 1800, 87),
('福建土笋冻', '泉州土笋冻', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Quanzhou%20bamboo%20shoot%20jelly&image_size=square', (SELECT id FROM categories WHERE name = '闽菜' LIMIT 1), '{"calories": 80, "protein": 8, "fat": 2, "carbs": 8}', 4.1, 800, 78),
('福建鱼丸汤', '福州鱼丸汤', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Fuzhou%20fish%20ball%20soup&image_size=square', (SELECT id FROM categories WHERE name = '闽菜' LIMIT 1), '{"calories": 180, "protein": 15, "fat": 8, "carbs": 12}', 4.2, 1500, 82),
('福建白斩鸭', '闽式白斩鸭', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Fujian%20white%20cut%20duck&image_size=square', (SELECT id FROM categories WHERE name = '闽菜' LIMIT 1), '{"calories": 320, "protein": 26, "fat": 22, "carbs": 3}', 4.3, 1000, 81),
('福建蒸蛋', '闽式蒸蛋', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Fujian%20steamed%20egg&image_size=square', (SELECT id FROM categories WHERE name = '闽菜' LIMIT 1), '{"calories": 150, "protein": 12, "fat": 10, "carbs": 5}', 4.0, 900, 76),
('福建红烧肉', '闽式红烧肉', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Fujian%20braised%20pork%20belly&image_size=square', (SELECT id FROM categories WHERE name = '闽菜' LIMIT 1), '{"calories": 480, "protein": 20, "fat": 38, "carbs": 15}', 4.4, 1300, 84);

-- 插入更多徽菜菜品 (50个)
INSERT INTO dishes (name, description, image_url, category_id, nutrition_facts, avg_rating, review_count, popularity_score) VALUES
('安徽臭鳜鱼', '臭鳜鱼', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Anhui%20stinky%20mandarin%20fish&image_size=square', (SELECT id FROM categories WHERE name = '徽菜' LIMIT 1), '{"calories": 320, "protein": 28, "fat": 20, "carbs": 8}', 4.5, 1400, 87),
('安徽毛豆腐', '徽州毛豆腐', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Huizhou%20hairy%20tofu&image_size=square', (SELECT id FROM categories WHERE name = '徽菜' LIMIT 1), '{"calories": 180, "protein": 12, "fat": 12, "carbs": 8}', 4.2, 800, 80),
('安徽火腿炖甲鱼', '火腿炖甲鱼', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Anhui%20ham%20stewed%20turtle&image_size=square', (SELECT id FROM categories WHERE name = '徽菜' LIMIT 1), '{"calories": 380, "protein": 32, "fat": 24, "carbs": 8}', 4.6, 1000, 88),
('安徽腌笃鲜', '徽州腌笃鲜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Huizhou%20pickled%20bamboo%20shoot%20soup&image_size=square', (SELECT id FROM categories WHERE name = '徽菜' LIMIT 1), '{"calories": 220, "protein": 18, "fat": 12, "carbs": 12}', 4.3, 900, 82),
('安徽红烧划水', '红烧划水', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Anhui%20braised%20fish%20slices&image_size=square', (SELECT id FROM categories WHERE name = '徽菜' LIMIT 1), '{"calories": 280, "protein": 25, "fat": 16, "carbs": 10}', 4.2, 700, 78),
('安徽蜜汁红芋', '蜜汁红芋', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Anhui%20honey%20glazed%20sweet%20potato&image_size=square', (SELECT id FROM categories WHERE name = '徽菜' LIMIT 1), '{"calories": 280, "protein": 4, "fat": 2, "carbs": 65}', 4.1, 600, 75),
('安徽白切羊肉', '徽式白切羊肉', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Anhui%20white%20cut%20mutton&image_size=square', (SELECT id FROM categories WHERE name = '徽菜' LIMIT 1), '{"calories": 320, "protein": 28, "fat": 22, "carbs": 2}', 4.0, 500, 72),
('安徽糖醋排骨', '徽式糖醋排骨', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Anhui%20sweet%20sour%20ribs&image_size=square', (SELECT id FROM categories WHERE name = '徽菜' LIMIT 1), '{"calories": 420, "protein": 26, "fat": 22, "carbs": 32}', 4.3, 1100, 81),
('安徽蒸蛋羹', '徽式蒸蛋羹', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Anhui%20steamed%20egg%20custard&image_size=square', (SELECT id FROM categories WHERE name = '徽菜' LIMIT 1), '{"calories": 150, "protein": 12, "fat": 10, "carbs": 5}', 4.1, 800, 77),
('安徽红烧肉', '徽式红烧肉', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Anhui%20braised%20pork%20belly&image_size=square', (SELECT id FROM categories WHERE name = '徽菜' LIMIT 1), '{"calories": 480, "protein": 20, "fat": 38, "carbs": 15}', 4.4, 1200, 83);

-- 插入更多国际美食 (80个)
INSERT INTO dishes (name, description, image_url, category_id, nutrition_facts, avg_rating, review_count, popularity_score) VALUES
('意大利披萨', '经典玛格丽特披萨', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Italian%20Margherita%20pizza&image_size=square', (SELECT id FROM categories WHERE name = '西餐' LIMIT 1), '{"calories": 520, "protein": 22, "fat": 18, "carbs": 68}', 4.5, 3000, 89),
('日式寿司', '三文鱼寿司', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Japanese%20salmon%20sushi&image_size=square', (SELECT id FROM categories WHERE name = '日料' LIMIT 1), '{"calories": 180, "protein": 12, "fat": 6, "carbs": 22}', 4.6, 2500, 90),
('韩式烤肉', '韩式牛肉烤肉', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Korean%20beef%20BBQ&image_size=square', (SELECT id FROM categories WHERE name = '韩料' LIMIT 1), '{"calories": 420, "protein": 32, "fat": 28, "carbs": 8}', 4.4, 2200, 87),
('泰式咖喱', '泰式绿咖喱鸡', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Thai%20green%20curry%20chicken&image_size=square', (SELECT id FROM categories WHERE name = '东南亚菜' LIMIT 1), '{"calories": 380, "protein": 25, "fat": 25, "carbs": 18}', 4.3, 1800, 85),
('印度咖喱', '印度鸡肉咖喱', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Indian%20chicken%20curry&image_size=square', (SELECT id FROM categories WHERE name = '印度菜' LIMIT 1), '{"calories": 350, "protein": 28, "fat": 20, "carbs": 15}', 4.2, 1500, 83),
('墨西哥卷饼', '墨西哥牛肉卷饼', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Mexican%20beef%20burrito&image_size=square', (SELECT id FROM categories WHERE name = '墨西哥菜' LIMIT 1), '{"calories": 480, "protein": 25, "fat": 22, "carbs": 48}', 4.1, 1200, 81),
('法式牛排', '法式煎牛排', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=French%20pan%20seared%20steak&image_size=square', (SELECT id FROM categories WHERE name = '西餐' LIMIT 1), '{"calories": 450, "protein": 35, "fat": 32, "carbs": 5}', 4.7, 2000, 92),
('德式香肠', '德式烤香肠', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=German%20grilled%20sausage&image_size=square', (SELECT id FROM categories WHERE name = '德国菜' LIMIT 1), '{"calories": 380, "protein": 18, "fat": 32, "carbs": 8}', 4.0, 800, 76),
('俄式罗宋汤', '俄式红菜汤', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=Russian%20borscht%20soup&image_size=square', (SELECT id FROM categories WHERE name = '俄国菜' LIMIT 1), '{"calories": 180, "protein": 8, "fat": 6, "carbs": 25}', 4.2, 600, 78),
('英式炸鱼薯条', '英式炸鱼薯条', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=British%20fish%20and%20chips&image_size=square', (SELECT id FROM categories WHERE name = '英国菜' LIMIT 1), '{"calories": 620, "protein": 28, "fat": 35, "carbs": 58}', 4.1, 1000, 79);