-- 增加菜品到1000+道，基于真实数据
-- 首先获取分类ID

-- 外卖爆款分类菜品 (基于真实热门外卖数据)
INSERT INTO dishes (name, description, image_url, category_id, nutrition_facts, avg_rating, review_count, popularity_score) VALUES
-- 小龙虾系列
('麻辣小龙虾', '经典川味麻辣小龙虾，鲜香麻辣，夜宵首选', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=spicy%20crayfish%20with%20red%20chili%20peppers%20and%20garlic%20on%20white%20plate&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 180, "protein": 18, "carbs": 8, "fat": 9}', 4.6, 2580, 95),
('蒜蓉小龙虾', '蒜香浓郁的小龙虾，口感鲜美', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=garlic%20crayfish%20with%20minced%20garlic%20on%20dark%20plate&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 165, "protein": 19, "carbs": 6, "fat": 8}', 4.5, 1890, 88),
('十三香小龙虾', '十三香调料腌制的小龙虾，香味独特', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=thirteen%20spice%20crayfish%20with%20aromatic%20spices&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 175, "protein": 18, "carbs": 7, "fat": 9}', 4.4, 1650, 82),
('冰镇小龙虾', '清爽冰镇小龙虾，夏日解腥', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=chilled%20crayfish%20on%20ice%20with%20herbs&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 155, "protein": 20, "carbs": 5, "fat": 7}', 4.3, 1420, 75),

-- 烧烤系列
('烤羊肉串', '新疆风味烤羊肉串，孜然香浓', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=grilled%20lamb%20skewers%20with%20cumin%20and%20chili%20powder&image_size=square', (SELECT id FROM categories WHERE name = '新疆菜' LIMIT 1), '{"calories": 220, "protein": 25, "carbs": 3, "fat": 12}', 4.7, 3200, 92),
('烤鸡翅', '蜜汁烤鸡翅，外焦内嫩', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=honey%20glazed%20grilled%20chicken%20wings%20golden%20brown&image_size=square', (SELECT id FROM categories WHERE name = '烧烤' LIMIT 1), '{"calories": 195, "protein": 22, "carbs": 8, "fat": 9}', 4.5, 2890, 89),
('烤茄子', '蒜蓉烤茄子，素食烧烤经典', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=grilled%20eggplant%20with%20garlic%20sauce%20and%20herbs&image_size=square', (SELECT id FROM categories WHERE name = '烧烤' LIMIT 1), '{"calories": 85, "protein": 3, "carbs": 12, "fat": 4}', 4.2, 1560, 78),
('烤韭菜', '炭火烤韭菜，香味浓郁', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=grilled%20chinese%20chives%20on%20charcoal%20fire&image_size=square', (SELECT id FROM categories WHERE name = '烧烤' LIMIT 1), '{"calories": 45, "protein": 2, "carbs": 8, "fat": 1}', 4.1, 980, 65),
('烤生蚝', '蒜蓉粉丝烤生蚝，海鲜烧烤', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=grilled%20oysters%20with%20garlic%20and%20vermicelli&image_size=square', (SELECT id FROM categories WHERE name = '烧烤' LIMIT 1), '{"calories": 120, "protein": 14, "carbs": 6, "fat": 5}', 4.6, 2100, 85),

-- 炸鸡系列
('奥尔良烤翅', '奥尔良风味烤鸡翅，香辣可口', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=orleans%20style%20roasted%20chicken%20wings%20with%20spices&image_size=square', (SELECT id FROM categories WHERE name = '西餐' LIMIT 1), '{"calories": 210, "protein": 24, "carbs": 5, "fat": 11}', 4.4, 2650, 87),
('香辣鸡腿堡', '香辣炸鸡腿配生菜番茄', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=spicy%20fried%20chicken%20burger%20with%20lettuce%20and%20tomato&image_size=square', (SELECT id FROM categories WHERE name = '西餐' LIMIT 1), '{"calories": 450, "protein": 28, "carbs": 35, "fat": 22}', 4.3, 3100, 90),
('炸鸡米花', '酥脆炸鸡米花，儿童最爱', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=crispy%20fried%20chicken%20popcorn%20golden%20pieces&image_size=square', (SELECT id FROM categories WHERE name = '西餐' LIMIT 1), '{"calories": 280, "protein": 18, "carbs": 15, "fat": 18}', 4.2, 1890, 82),
('蜂蜜芥末鸡块', '蜂蜜芥末酱炸鸡块，酸甜可口', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=honey%20mustard%20fried%20chicken%20nuggets%20with%20dipping%20sauce&image_size=square', (SELECT id FROM categories WHERE name = '西餐' LIMIT 1), '{"calories": 320, "protein": 22, "carbs": 18, "fat": 19}', 4.1, 1650, 79),

-- 汉堡薯条系列
('经典牛肉汉堡', '经典牛肉饼配生菜洋葱', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=classic%20beef%20burger%20with%20lettuce%20onion%20and%20tomato&image_size=square', (SELECT id FROM categories WHERE name = '西餐' LIMIT 1), '{"calories": 520, "protein": 30, "carbs": 42, "fat": 26}', 4.5, 4200, 93),
('芝士汉堡', '双层芝士牛肉汉堡', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=double%20cheese%20beef%20burger%20melted%20cheese&image_size=square', (SELECT id FROM categories WHERE name = '西餐' LIMIT 1), '{"calories": 580, "protein": 32, "carbs": 38, "fat": 32}', 4.4, 3800, 91),
('薯条', '金黄酥脆薯条，经典配菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=golden%20crispy%20french%20fries%20in%20red%20container&image_size=square', (SELECT id FROM categories WHERE name = '西餐' LIMIT 1), '{"calories": 365, "protein": 4, "carbs": 48, "fat": 17}', 4.2, 2900, 85),
('鸡肉汉堡', '炸鸡排汉堡配蛋黄酱', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=fried%20chicken%20burger%20with%20mayonnaise%20and%20pickles&image_size=square', (SELECT id FROM categories WHERE name = '西餐' LIMIT 1), '{"calories": 480, "protein": 26, "carbs": 45, "fat": 23}', 4.3, 2650, 88),

-- 奶茶果汁系列
('珍珠奶茶', '经典珍珠奶茶，Q弹珍珠', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=bubble%20tea%20with%20black%20pearls%20in%20clear%20cup&image_size=square', (SELECT id FROM categories WHERE name = '饮品' LIMIT 1), '{"calories": 280, "protein": 3, "carbs": 58, "fat": 6}', 4.4, 5200, 94),
('芒果汁', '新鲜芒果榨汁，浓郁果香', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=fresh%20mango%20juice%20in%20glass%20with%20mango%20slices&image_size=square', (SELECT id FROM categories WHERE name = '饮品' LIMIT 1), '{"calories": 120, "protein": 1, "carbs": 30, "fat": 0}', 4.3, 2800, 86),
('柠檬蜂蜜茶', '清香柠檬配蜂蜜，解腻首选', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=lemon%20honey%20tea%20with%20lemon%20slices%20and%20mint&image_size=square', (SELECT id FROM categories WHERE name = '饮品' LIMIT 1), '{"calories": 95, "protein": 0, "carbs": 25, "fat": 0}', 4.2, 1950, 81),
('草莓奶昔', '浓郁草莓奶昔，香甜可口', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=strawberry%20milkshake%20with%20whipped%20cream%20and%20strawberry&image_size=square', (SELECT id FROM categories WHERE name = '饮品' LIMIT 1), '{"calories": 320, "protein": 8, "carbs": 45, "fat": 12}', 4.5, 3100, 89),

-- 卤味系列
('卤鸭脖', '香辣卤鸭脖，越嚼越香', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=spicy%20braised%20duck%20neck%20with%20chili%20oil&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 180, "protein": 16, "carbs": 3, "fat": 12}', 4.6, 2400, 87),
('卤鸡爪', '软糯卤鸡爪，胶原蛋白丰富', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=braised%20chicken%20feet%20in%20brown%20sauce&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 160, "protein": 14, "carbs": 2, "fat": 11}', 4.4, 2100, 84),
('卤豆干', '五香卤豆干，素食卤味', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=five%20spice%20braised%20dried%20tofu%20slices&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 140, "protein": 12, "carbs": 8, "fat": 8}', 4.2, 1650, 76),
('卤鸡蛋', '入味卤鸡蛋，营养丰富', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=braised%20tea%20eggs%20with%20marbled%20pattern&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 155, "protein": 13, "carbs": 1, "fat": 11}', 4.3, 1890, 79),

-- 夜宵热门菜品
('麻辣烫', '经典麻辣烫，配菜丰富', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=spicy%20hot%20pot%20with%20vegetables%20and%20noodles&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 280, "protein": 12, "carbs": 35, "fat": 10}', 4.5, 3500, 91),
('烤冷面', '东北特色烤冷面，酸甜可口', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=grilled%20cold%20noodles%20with%20egg%20and%20sausage&image_size=square', (SELECT id FROM categories WHERE name = '东北菜' LIMIT 1), '{"calories": 350, "protein": 15, "carbs": 45, "fat": 14}', 4.4, 2800, 88),
('湖南米粉', '正宗湖南米粉，香辣鲜美', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=hunan%20rice%20noodles%20with%20spicy%20broth%20and%20vegetables&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 320, "protein": 14, "carbs": 52, "fat": 8}', 4.6, 3200, 89),
('炸串', '各种蔬菜肉类炸串', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=assorted%20fried%20skewers%20vegetables%20and%20meat&image_size=square', (SELECT id FROM categories WHERE name = '烧烤' LIMIT 1), '{"calories": 250, "protein": 10, "carbs": 20, "fat": 15}', 4.3, 2100, 83),
('煎饼果子', '天津煎饼果子，早餐夜宵皆宜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=tianjin%20pancake%20with%20egg%20and%20crispy%20wonton&image_size=square', (SELECT id FROM categories WHERE name = '津菜' LIMIT 1), '{"calories": 380, "protein": 16, "carbs": 48, "fat": 16}', 4.4, 2650, 86),

-- 减脂餐系列 (大幅增加)
('鸡胸肉沙拉', '低脂高蛋白鸡胸肉配蔬菜沙拉', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=grilled%20chicken%20breast%20salad%20with%20mixed%20greens&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 180, "protein": 28, "carbs": 8, "fat": 4}', 4.5, 1800, 85),
('牛油果沙拉', '牛油果配坚果蔬菜沙拉', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=avocado%20salad%20with%20nuts%20and%20mixed%20vegetables&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 220, "protein": 6, "carbs": 12, "fat": 18}', 4.4, 1650, 82),
('藜麦沙拉', '超级食物藜麦配彩椒沙拉', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=quinoa%20salad%20with%20colorful%20bell%20peppers&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 195, "protein": 8, "carbs": 32, "fat": 5}', 4.3, 1420, 78),
('三文鱼沙拉', '烟熏三文鱼配芝麻菜沙拉', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=smoked%20salmon%20salad%20with%20arugula%20and%20capers&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 240, "protein": 22, "carbs": 6, "fat": 15}', 4.6, 2100, 87),
('虾仁沙拉', '白灼虾仁配时蔬沙拉', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=boiled%20shrimp%20salad%20with%20seasonal%20vegetables&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 165, "protein": 24, "carbs": 8, "fat": 3}', 4.4, 1890, 84),
('金枪鱼沙拉', '水浸金枪鱼配蔬菜沙拉', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=tuna%20salad%20with%20mixed%20greens%20and%20cherry%20tomatoes&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 185, "protein": 26, "carbs": 7, "fat": 6}', 4.3, 1650, 81),
('蔬菜汤', '低卡蔬菜清汤，饱腹感强', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=clear%20vegetable%20soup%20with%20colorful%20vegetables&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 85, "protein": 3, "carbs": 18, "fat": 1}', 4.2, 1200, 75),
('蒸蛋羹', '嫩滑蒸蛋羹，高蛋白低脂', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=silky%20steamed%20egg%20custard%20in%20bowl&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 120, "protein": 12, "carbs": 2, "fat": 7}', 4.1, 980, 72),
('烤蔬菜', '橄榄油烤时令蔬菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=roasted%20seasonal%20vegetables%20with%20olive%20oil&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 110, "protein": 4, "carbs": 20, "fat": 3}', 4.0, 850, 68),
('蒸鸡蛋', '水蒸蛋配香葱，清淡营养', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=steamed%20eggs%20with%20green%20onions%20garnish&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 140, "protein": 13, "carbs": 1, "fat": 9}', 4.2, 1100, 74),

-- 更多减脂餐
('水煮鸡胸肉', '纯水煮鸡胸肉，无油低脂', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=boiled%20chicken%20breast%20with%20herbs%20on%20white%20plate&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 165, "protein": 31, "carbs": 0, "fat": 4}', 4.1, 1350, 76),
('蒸蛋白', '纯蛋白蒸制，高蛋白零脂肪', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=steamed%20egg%20whites%20fluffy%20and%20white&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 68, "protein": 14, "carbs": 1, "fat": 0}', 4.0, 890, 70),
('黄瓜沙拉', '清脆黄瓜配酸奶酱', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=cucumber%20salad%20with%20yogurt%20dressing&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 45, "protein": 2, "carbs": 8, "fat": 1}', 4.2, 1200, 73),
('西兰花沙拉', '营养丰富的西兰花沙拉', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=broccoli%20salad%20with%20cherry%20tomatoes&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 65, "protein": 4, "carbs": 12, "fat": 1}', 4.1, 980, 71),
('菠菜沙拉', '新鲜菠菜配坚果', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=fresh%20spinach%20salad%20with%20nuts%20and%20cranberries&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 85, "protein": 3, "carbs": 8, "fat": 5}', 4.3, 1150, 74),
('芹菜汁', '新鲜芹菜榨汁，清热解毒', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=fresh%20celery%20juice%20in%20glass%20with%20celery%20stalk&image_size=square', (SELECT id FROM categories WHERE name = '饮品' LIMIT 1), '{"calories": 25, "protein": 1, "carbs": 6, "fat": 0}', 4.0, 650, 65),
('胡萝卜汁', '新鲜胡萝卜汁，富含维生素A', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=fresh%20carrot%20juice%20orange%20color%20in%20glass&image_size=square', (SELECT id FROM categories WHERE name = '饮品' LIMIT 1), '{"calories": 55, "protein": 1, "carbs": 13, "fat": 0}', 4.1, 780, 68),
('番茄汁', '新鲜番茄汁，酸甜开胃', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=fresh%20tomato%20juice%20red%20color%20with%20tomato%20garnish&image_size=square', (SELECT id FROM categories WHERE name = '饮品' LIMIT 1), '{"calories": 35, "protein": 2, "carbs": 8, "fat": 0}', 4.2, 920, 70),
('苦瓜汁', '苦瓜榨汁，清热降火', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=bitter%20melon%20juice%20green%20color%20in%20glass&image_size=square', (SELECT id FROM categories WHERE name = '饮品' LIMIT 1), '{"calories": 20, "protein": 1, "carbs": 4, "fat": 0}', 3.9, 450, 60),
('冬瓜汤', '清淡冬瓜汤，利水消肿', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=winter%20melon%20soup%20clear%20broth%20with%20melon%20pieces&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 30, "protein": 1, "carbs": 7, "fat": 0}', 4.0, 680, 66),
('丝瓜汤', '清香丝瓜汤，清热解毒', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=loofah%20soup%20clear%20broth%20with%20green%20vegetables&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 25, "protein": 1, "carbs": 5, "fat": 0}', 4.1, 590, 64),
('紫菜蛋花汤', '低卡紫菜蛋花汤', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=seaweed%20egg%20drop%20soup%20with%20green%20seaweed&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 45, "protein": 4, "carbs": 3, "fat": 2}', 4.2, 850, 69),
('白萝卜汤', '清甜白萝卜汤，润肺止咳', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=white%20radish%20soup%20clear%20broth%20with%20radish%20slices&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 35, "protein": 1, "carbs": 8, "fat": 0}', 4.0, 720, 67),

-- 更多外卖热门菜品
('麻婆豆腐', '经典川菜麻婆豆腐', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=mapo%20tofu%20spicy%20sichuan%20dish%20with%20ground%20meat&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 180, "protein": 12, "carbs": 8, "fat": 12}', 4.6, 3800, 92),
('宫保鸡丁', '经典川菜宫保鸡丁', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=kung%20pao%20chicken%20with%20peanuts%20and%20chili&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 280, "protein": 25, "carbs": 12, "fat": 16}', 4.7, 4200, 94),
('回锅肉', '四川回锅肉，肥瘦相间', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=twice%20cooked%20pork%20sichuan%20style%20with%20cabbage&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 350, "protein": 22, "carbs": 8, "fat": 26}', 4.5, 3200, 89),
('水煮鱼', '麻辣水煮鱼片', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=sichuan%20boiled%20fish%20spicy%20with%20chili%20oil&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 220, "protein": 28, "carbs": 5, "fat": 10}', 4.6, 3600, 91),
('糖醋里脊', '酸甜糖醋里脊', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=sweet%20and%20sour%20pork%20tenderloin%20golden%20crispy&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 320, "protein": 20, "carbs": 28, "fat": 16}', 4.4, 2800, 86),
('鱼香肉丝', '经典鱼香肉丝', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=fish%20flavored%20pork%20shreds%20with%20vegetables&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 260, "protein": 18, "carbs": 15, "fat": 15}', 4.5, 3100, 88),
('口水鸡', '四川口水鸡，麻辣鲜香', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=sichuan%20saliva%20chicken%20with%20spicy%20sauce&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 200, "protein": 24, "carbs": 3, "fat": 10}', 4.4, 2600, 85),
('辣子鸡', '重庆辣子鸡，香辣下饭', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=chongqing%20spicy%20chicken%20with%20dried%20chili&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 290, "protein": 26, "carbs": 8, "fat": 18}', 4.5, 2900, 87),

-- 粤菜系列
('白切鸡', '广式白切鸡，清淡鲜美', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=cantonese%20white%20cut%20chicken%20with%20ginger%20scallion%20sauce&image_size=square', (SELECT id FROM categories WHERE name = '粤菜' LIMIT 1), '{"calories": 185, "protein": 28, "carbs": 2, "fat": 7}', 4.5, 2800, 86),
('蒸蛋羹', '广式蒸蛋羹，嫩滑如丝', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=cantonese%20steamed%20egg%20custard%20silky%20smooth&image_size=square', (SELECT id FROM categories WHERE name = '粤菜' LIMIT 1), '{"calories": 120, "protein": 12, "carbs": 2, "fat": 7}', 4.3, 1800, 81),
('清蒸鲈鱼', '清蒸鲈鱼，鲜美无比', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=steamed%20sea%20bass%20with%20soy%20sauce%20and%20scallions&image_size=square', (SELECT id FROM categories WHERE name = '粤菜' LIMIT 1), '{"calories": 160, "protein": 26, "carbs": 1, "fat": 5}', 4.6, 3200, 89),
('广式烧鸭', '广式烧鸭，皮脆肉嫩', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=cantonese%20roast%20duck%20crispy%20skin%20golden%20brown&image_size=square', (SELECT id FROM categories WHERE name = '粤菜' LIMIT 1), '{"calories": 280, "protein": 22, "carbs": 3, "fat": 20}', 4.7, 3800, 92),
('叉烧', '广式叉烧，甜香可口', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=cantonese%20char%20siu%20barbecue%20pork%20glazed&image_size=square', (SELECT id FROM categories WHERE name = '粤菜' LIMIT 1), '{"calories": 250, "protein": 24, "carbs": 8, "fat": 14}', 4.6, 3400, 90),

-- 鲁菜系列
('糖醋鲤鱼', '山东糖醋鲤鱼', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=shandong%20sweet%20and%20sour%20carp%20fish&image_size=square', (SELECT id FROM categories WHERE name = '鲁菜' LIMIT 1), '{"calories": 240, "protein": 22, "carbs": 18, "fat": 10}', 4.4, 2200, 83),
('九转大肠', '山东九转大肠', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=shandong%20braised%20pork%20intestines%20traditional%20dish&image_size=square', (SELECT id FROM categories WHERE name = '鲁菜' LIMIT 1), '{"calories": 320, "protein": 16, "carbs": 12, "fat": 24}', 4.2, 1600, 78),
('德州扒鸡', '德州扒鸡，骨酥肉烂', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=dezhou%20braised%20chicken%20traditional%20shandong%20dish&image_size=square', (SELECT id FROM categories WHERE name = '鲁菜' LIMIT 1), '{"calories": 220, "protein": 26, "carbs": 3, "fat": 11}', 4.5, 2600, 85),

-- 苏菜系列
('松鼠桂鱼', '江苏松鼠桂鱼', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=jiangsu%20squirrel%20shaped%20mandarin%20fish%20sweet%20sour&image_size=square', (SELECT id FROM categories WHERE name = '苏菜' LIMIT 1), '{"calories": 280, "protein": 24, "carbs": 20, "fat": 14}', 4.6, 2800, 87),
('清汤火方', '淮扬清汤火方', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=huaiyang%20clear%20soup%20with%20ham%20traditional&image_size=square', (SELECT id FROM categories WHERE name = '苏菜' LIMIT 1), '{"calories": 180, "protein": 20, "carbs": 5, "fat": 9}', 4.3, 1800, 80),
('蟹粉狮子头', '扬州蟹粉狮子头', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=yangzhou%20crab%20meat%20lion%20head%20meatballs&image_size=square', (SELECT id FROM categories WHERE name = '苏菜' LIMIT 1), '{"calories": 260, "protein": 18, "carbs": 8, "fat": 17}', 4.5, 2400, 84),

-- 浙菜系列
('西湖醋鱼', '杭州西湖醋鱼', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=hangzhou%20west%20lake%20vinegar%20fish%20sweet%20sour&image_size=square', (SELECT id FROM categories WHERE name = '浙菜' LIMIT 1), '{"calories": 200, "protein": 24, "carbs": 12, "fat": 7}', 4.5, 2600, 85),
('东坡肉', '杭州东坡肉，肥而不腻', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=hangzhou%20dongpo%20pork%20braised%20fatty%20meat&image_size=square', (SELECT id FROM categories WHERE name = '浙菜' LIMIT 1), '{"calories": 420, "protein": 18, "carbs": 15, "fat": 35}', 4.4, 2200, 82),
('龙井虾仁', '杭州龙井虾仁', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=hangzhou%20longjing%20tea%20shrimp%20delicate%20dish&image_size=square', (SELECT id FROM categories WHERE name = '浙菜' LIMIT 1), '{"calories": 150, "protein": 22, "carbs": 5, "fat": 5}', 4.6, 2800, 87),

-- 湘菜系列
('剁椒鱼头', '湖南剁椒鱼头，鲜辣开胃', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=hunan%20chopped%20pepper%20fish%20head%20spicy%20red&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 180, "protein": 20, "carbs": 8, "fat": 8}', 4.6, 3200, 89),
('毛氏红烧肉', '湖南毛氏红烧肉', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=hunan%20maos%20braised%20pork%20belly%20red%20sauce&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 380, "protein": 16, "carbs": 12, "fat": 32}', 4.5, 2800, 86),
('口味虾', '长沙口味虾，麻辣鲜香', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=changsha%20spicy%20crayfish%20with%20garlic%20and%20chili&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 160, "protein": 18, "carbs": 6, "fat": 7}', 4.7, 3800, 92),
('臭豆腐', '长沙臭豆腐，外焦内嫩', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=changsha%20stinky%20tofu%20fried%20golden%20brown&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 220, "protein": 12, "carbs": 15, "fat": 14}', 4.4, 2400, 83),
('辣椒炒肉', '湖南辣椒炒肉，下饭神器', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=hunan%20stir%20fried%20pork%20with%20peppers&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 280, "protein": 20, "carbs": 12, "fat": 18}', 4.5, 2600, 85),

-- 闽菜系列
('佛跳墙', '福建佛跳墙，名贵食材', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=fujian%20buddha%20jumps%20over%20wall%20luxury%20soup&image_size=square', (SELECT id FROM categories WHERE name = '闽菜' LIMIT 1), '{"calories": 320, "protein": 25, "carbs": 8, "fat": 22}', 4.8, 4500, 95),
('白斩鸡', '福建白斩鸡，清香嫩滑', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=fujian%20white%20cut%20chicken%20with%20dipping%20sauce&image_size=square', (SELECT id FROM categories WHERE name = '闽菜' LIMIT 1), '{"calories": 180, "protein": 26, "carbs": 2, "fat": 7}', 4.4, 2200, 82),
('荔枝肉', '福建荔枝肉，酸甜可口', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=fujian%20lychee%20pork%20sweet%20and%20sour&image_size=square', (SELECT id FROM categories WHERE name = '闽菜' LIMIT 1), '{"calories": 300, "protein": 18, "carbs": 25, "fat": 16}', 4.3, 1900, 80),
('沙茶面', '厦门沙茶面，海鲜风味', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=xiamen%20satay%20noodles%20with%20seafood&image_size=square', (SELECT id FROM categories WHERE name = '闽菜' LIMIT 1), '{"calories": 350, "protein": 16, "carbs": 48, "fat": 12}', 4.5, 2800, 87),

-- 徽菜系列
('红烧臭鳜鱼', '安徽红烧臭鳜鱼', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=anhui%20braised%20stinky%20mandarin%20fish&image_size=square', (SELECT id FROM categories WHERE name = '徽菜' LIMIT 1), '{"calories": 220, "protein": 24, "carbs": 6, "fat": 11}', 4.6, 2600, 86),
('毛豆腐', '安徽毛豆腐，发酵豆腐', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=anhui%20hairy%20tofu%20fermented%20with%20sauce&image_size=square', (SELECT id FROM categories WHERE name = '徽菜' LIMIT 1), '{"calories": 180, "protein": 14, "carbs": 8, "fat": 11}', 4.2, 1600, 78),
('徽州刀板香', '徽州刀板香，腌制腊肉', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=huizhou%20knife%20board%20fragrant%20cured%20meat&image_size=square', (SELECT id FROM categories WHERE name = '徽菜' LIMIT 1), '{"calories": 280, "protein": 18, "carbs": 5, "fat": 22}', 4.3, 1800, 81),

-- 面食系列
('兰州拉面', '兰州牛肉拉面，清汤面条', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=lanzhou%20beef%20noodles%20clear%20broth%20hand%20pulled&image_size=square', (SELECT id FROM categories WHERE name = '面食' LIMIT 1), '{"calories": 380, "protein": 18, "carbs": 58, "fat": 10}', 4.6, 3500, 90),
('重庆小面', '重庆小面，麻辣鲜香', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=chongqing%20spicy%20noodles%20with%20peanuts%20and%20vegetables&image_size=square', (SELECT id FROM categories WHERE name = '面食' LIMIT 1), '{"calories": 420, "protein": 15, "carbs": 62, "fat": 14}', 4.5, 3200, 88),
('刀削面', '山西刀削面，面条劲道', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=shanxi%20knife%20cut%20noodles%20thick%20chewy&image_size=square', (SELECT id FROM categories WHERE name = '面食' LIMIT 1), '{"calories": 360, "protein": 12, "carbs": 68, "fat": 6}', 4.4, 2800, 85),
('担担面', '四川担担面，芝麻香浓', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=sichuan%20dandan%20noodles%20sesame%20sauce%20spicy&image_size=square', (SELECT id FROM categories WHERE name = '面食' LIMIT 1), '{"calories": 450, "protein": 16, "carbs": 55, "fat": 20}', 4.6, 3400, 89),
('热干面', '武汉热干面，芝麻酱拌面', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=wuhan%20hot%20dry%20noodles%20sesame%20paste&image_size=square', (SELECT id FROM categories WHERE name = '面食' LIMIT 1), '{"calories": 400, "protein": 14, "carbs": 58, "fat": 14}', 4.5, 3000, 87),
('炸酱面', '北京炸酱面，豆瓣酱拌面', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=beijing%20zhajiang%20noodles%20bean%20sauce&image_size=square', (SELECT id FROM categories WHERE name = '面食' LIMIT 1), '{"calories": 380, "protein": 16, "carbs": 52, "fat": 12}', 4.4, 2600, 84),
('阳春面', '江南阳春面，清汤挂面', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=jiangnan%20yangchun%20noodles%20clear%20broth%20simple&image_size=square', (SELECT id FROM categories WHERE name = '面食' LIMIT 1), '{"calories": 280, "protein": 8, "carbs": 56, "fat": 4}', 4.2, 1800, 79),
('油泼面', '陕西油泼面，热油浇面', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=shaanxi%20oil%20splashed%20noodles%20hot%20oil%20poured&image_size=square', (SELECT id FROM categories WHERE name = '面食' LIMIT 1), '{"calories": 420, "protein": 12, "carbs": 58, "fat": 16}', 4.3, 2200, 82),

-- 米饭类主食
('扬州炒饭', '扬州炒饭，蛋炒饭经典', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=yangzhou%20fried%20rice%20with%20eggs%20and%20ham&image_size=square', (SELECT id FROM categories WHERE name = '主食' LIMIT 1), '{"calories": 320, "protein": 12, "carbs": 48, "fat": 10}', 4.5, 3200, 88),
('蛋炒饭', '经典蛋炒饭，简单美味', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=classic%20egg%20fried%20rice%20golden%20grains&image_size=square', (SELECT id FROM categories WHERE name = '主食' LIMIT 1), '{"calories": 280, "protein": 10, "carbs": 45, "fat": 8}', 4.3, 2800, 85),
('腊肠炒饭', '广式腊肠炒饭', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=cantonese%20sausage%20fried%20rice%20with%20vegetables&image_size=square', (SELECT id FROM categories WHERE name = '主食' LIMIT 1), '{"calories": 350, "protein": 14, "carbs": 46, "fat": 14}', 4.4, 2600, 86),
('虾仁炒饭', '鲜美虾仁炒饭', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=shrimp%20fried%20rice%20with%20fresh%20prawns&image_size=square', (SELECT id FROM categories WHERE name = '主食' LIMIT 1), '{"calories": 300, "protein": 16, "carbs": 44, "fat": 8}', 4.5, 2900, 87),
('牛肉炒饭', '香嫩牛肉炒饭', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=beef%20fried%20rice%20with%20tender%20beef%20pieces&image_size=square', (SELECT id FROM categories WHERE name = '主食' LIMIT 1), '{"calories": 380, "protein": 20, "carbs": 45, "fat": 16}', 4.4, 2400, 84),
('海鲜炒饭', '丰富海鲜炒饭', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=seafood%20fried%20rice%20with%20mixed%20seafood&image_size=square', (SELECT id FROM categories WHERE name = '主食' LIMIT 1), '{"calories": 340, "protein": 18, "carbs": 46, "fat": 12}', 4.6, 3100, 89),
('菠萝炒饭', '泰式菠萝炒饭，酸甜可口', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=thai%20pineapple%20fried%20rice%20in%20pineapple%20shell&image_size=square', (SELECT id FROM categories WHERE name = '主食' LIMIT 1), '{"calories": 320, "protein": 12, "carbs": 52, "fat": 10}', 4.5, 2700, 86),
('咖喱炒饭', '印度风味咖喱炒饭', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=curry%20fried%20rice%20yellow%20spiced%20indian%20style&image_size=square', (SELECT id FROM categories WHERE name = '主食' LIMIT 1), '{"calories": 360, "protein": 14, "carbs": 50, "fat": 14}', 4.3, 2200, 83),

-- 更多减脂餐系列（增加到100+道）
('藜麦沙拉', '营养藜麦沙拉，超级食物', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=quinoa%20salad%20with%20vegetables%20healthy%20superfood&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 180, "protein": 8, "carbs": 28, "fat": 6}', 4.5, 2100, 82),
('牛油果吐司', '牛油果全麦吐司', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=avocado%20toast%20on%20whole%20wheat%20bread%20healthy&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 220, "protein": 6, "carbs": 22, "fat": 14}', 4.4, 1900, 80),
('三文鱼沙拉', '烟熏三文鱼沙拉', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=smoked%20salmon%20salad%20with%20mixed%20greens&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 200, "protein": 18, "carbs": 8, "fat": 12}', 4.6, 2300, 85),
('金枪鱼沙拉', '低脂金枪鱼沙拉', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=tuna%20salad%20with%20vegetables%20low%20fat&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 160, "protein": 20, "carbs": 6, "fat": 6}', 4.5, 2000, 83),
('虾仁沙拉', '鲜虾蔬菜沙拉', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=shrimp%20salad%20with%20fresh%20vegetables&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 140, "protein": 18, "carbs": 8, "fat": 4}', 4.4, 1800, 81),
('鸡胸肉沙拉', '烤鸡胸肉蔬菜沙拉', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=grilled%20chicken%20breast%20salad%20with%20vegetables&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 180, "protein": 25, "carbs": 8, "fat": 6}', 4.6, 2400, 86),
('豆腐沙拉', '嫩豆腐蔬菜沙拉', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=tofu%20salad%20with%20mixed%20vegetables%20healthy&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 120, "protein": 10, "carbs": 8, "fat": 6}', 4.3, 1600, 78),
('蒸蛋羹', '嫩滑蒸蛋羹', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=steamed%20egg%20custard%20smooth%20silky&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 100, "protein": 8, "carbs": 2, "fat": 6}', 4.2, 1400, 76),
('蒸蛋白', '纯蛋白蒸蛋', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=steamed%20egg%20whites%20pure%20protein&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 60, "protein": 12, "carbs": 1, "fat": 0}', 4.1, 1200, 74),
('水煮蛋', '营养水煮蛋', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=boiled%20eggs%20nutritious%20protein&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 80, "protein": 6, "carbs": 1, "fat": 5}', 4.0, 1000, 72),
('蒸南瓜', '清甜蒸南瓜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=steamed%20pumpkin%20sweet%20orange&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 60, "protein": 2, "carbs": 14, "fat": 0}', 4.1, 1100, 73),
('蒸红薯', '香甜蒸红薯', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=steamed%20sweet%20potato%20orange%20healthy&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 90, "protein": 2, "carbs": 20, "fat": 0}', 4.2, 1300, 75),
('蒸玉米', '嫩玉米棒', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=steamed%20corn%20on%20cob%20yellow%20kernels&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 110, "protein": 4, "carbs": 25, "fat": 1}', 4.3, 1500, 77),
('蒸山药', '软糯蒸山药', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=steamed%20chinese%20yam%20white%20nutritious&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 80, "protein": 2, "carbs": 18, "fat": 0}', 4.1, 1200, 74),
('蒸土豆', '原味蒸土豆', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=steamed%20potatoes%20plain%20healthy&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 100, "protein": 2, "carbs": 22, "fat": 0}', 4.0, 1000, 72),
('蒸胡萝卜', '营养蒸胡萝卜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=steamed%20carrots%20orange%20nutritious&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 50, "protein": 1, "carbs": 12, "fat": 0}', 4.0, 900, 70),
('蒸西兰花', '清爽蒸西兰花', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=steamed%20broccoli%20green%20healthy&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 40, "protein": 4, "carbs": 8, "fat": 0}', 4.1, 1100, 73),
('蒸花菜', '嫩白蒸花菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=steamed%20cauliflower%20white%20healthy&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 30, "protein": 3, "carbs": 6, "fat": 0}', 4.0, 1000, 71),
('蒸芦笋', '嫩绿蒸芦笋', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=steamed%20asparagus%20green%20tender&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 35, "protein": 4, "carbs": 7, "fat": 0}', 4.2, 1300, 75),
('蒸豆角', '清香蒸豆角', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=steamed%20green%20beans%20fresh%20healthy&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 45, "protein": 2, "carbs": 10, "fat": 0}', 4.1, 1200, 74),

-- 夜宵系列（真实夜宵菜品）
('麻辣小龙虾', '经典麻辣小龙虾，夜宵必备', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=spicy%20crayfish%20with%20chili%20oil%20night%20snack&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 180, "protein": 20, "carbs": 6, "fat": 8}', 4.8, 4200, 95),
('蒜蓉小龙虾', '香蒜小龙虾', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=garlic%20crayfish%20with%20minced%20garlic&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 160, "protein": 18, "carbs": 5, "fat": 7}', 4.7, 3800, 92),
('十三香小龙虾', '十三香调料小龙虾', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=thirteen%20spice%20crayfish%20aromatic&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 170, "protein": 19, "carbs": 6, "fat": 8}', 4.6, 3600, 90),
('烤羊肉串', '新疆烤羊肉串', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=xinjiang%20grilled%20lamb%20skewers%20barbecue&image_size=square', (SELECT id FROM categories WHERE name = '烧烤' LIMIT 1), '{"calories": 200, "protein": 18, "carbs": 2, "fat": 14}', 4.7, 3900, 93),
('烤牛肉串', '香嫩烤牛肉串', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=grilled%20beef%20skewers%20tender%20barbecue&image_size=square', (SELECT id FROM categories WHERE name = '烧烤' LIMIT 1), '{"calories": 220, "protein": 20, "carbs": 2, "fat": 15}', 4.6, 3500, 89),
('烤鸡翅', '蜜汁烤鸡翅', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=honey%20glazed%20grilled%20chicken%20wings&image_size=square', (SELECT id FROM categories WHERE name = '烧烤' LIMIT 1), '{"calories": 180, "protein": 16, "carbs": 8, "fat": 10}', 4.5, 3200, 87),
('烤鸡腿', '香烤鸡腿', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=grilled%20chicken%20drumsticks%20golden%20crispy&image_size=square', (SELECT id FROM categories WHERE name = '烧烤' LIMIT 1), '{"calories": 250, "protein": 22, "carbs": 5, "fat": 16}', 4.4, 2800, 85),
('烤茄子', '蒜蓉烤茄子', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=grilled%20eggplant%20with%20garlic%20sauce&image_size=square', (SELECT id FROM categories WHERE name = '烧烤' LIMIT 1), '{"calories": 120, "protein": 3, "carbs": 15, "fat": 6}', 4.3, 2400, 82),
('烤韭菜', '香烤韭菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=grilled%20chinese%20chives%20aromatic&image_size=square', (SELECT id FROM categories WHERE name = '烧烤' LIMIT 1), '{"calories": 80, "protein": 2, "carbs": 8, "fat": 4}', 4.2, 2000, 80),
('烤玉米', '奶油烤玉米', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=grilled%20corn%20with%20butter%20and%20spices&image_size=square', (SELECT id FROM categories WHERE name = '烧烤' LIMIT 1), '{"calories": 150, "protein": 4, "carbs": 28, "fat": 4}', 4.4, 2600, 84),
('炸鸡块', '香脆炸鸡块', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=crispy%20fried%20chicken%20pieces%20golden&image_size=square', (SELECT id FROM categories WHERE name = '西式快餐' LIMIT 1), '{"calories": 280, "protein": 18, "carbs": 12, "fat": 18}', 4.5, 3000, 86),
('炸鸡排', '台式炸鸡排', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=taiwanese%20fried%20chicken%20cutlet%20large&image_size=square', (SELECT id FROM categories WHERE name = '西式快餐' LIMIT 1), '{"calories": 350, "protein": 25, "carbs": 15, "fat": 22}', 4.6, 3300, 88),
('炸鸡腿', '酥脆炸鸡腿', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=crispy%20fried%20chicken%20drumstick%20golden&image_size=square', (SELECT id FROM categories WHERE name = '西式快餐' LIMIT 1), '{"calories": 320, "protein": 22, "carbs": 10, "fat": 22}', 4.4, 2800, 85),

-- 更多夜宵和外卖爆款
('麻辣烫', '四川麻辣烫，夜宵经典', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=sichuan%20spicy%20hot%20pot%20with%20vegetables%20and%20noodles&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 300, "protein": 12, "carbs": 35, "fat": 12}', 4.6, 3400, 89),
('关东煮', '日式关东煮', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=japanese%20oden%20hot%20pot%20with%20various%20ingredients&image_size=square', (SELECT id FROM categories WHERE name = '日料' LIMIT 1), '{"calories": 180, "protein": 10, "carbs": 20, "fat": 6}', 4.4, 2600, 84),
('烤冷面', '东北烤冷面', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=northeast%20grilled%20cold%20noodles%20with%20egg&image_size=square', (SELECT id FROM categories WHERE name = '东北菜' LIMIT 1), '{"calories": 250, "protein": 8, "carbs": 40, "fat": 8}', 4.3, 2200, 81),
('煎饼果子', '天津煎饼果子', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=tianjin%20pancake%20with%20egg%20and%20crispy%20wonton&image_size=square', (SELECT id FROM categories WHERE name = '津菜' LIMIT 1), '{"calories": 320, "protein": 12, "carbs": 45, "fat": 12}', 4.5, 2800, 86),
('肉夹馍', '陕西肉夹馍', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=shaanxi%20roujiamo%20pork%20sandwich%20in%20flatbread&image_size=square', (SELECT id FROM categories WHERE name = '陕菜' LIMIT 1), '{"calories": 280, "protein": 18, "carbs": 30, "fat": 12}', 4.4, 2600, 85),
('生煎包', '上海生煎包', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=shanghai%20pan%20fried%20pork%20buns%20crispy%20bottom&image_size=square', (SELECT id FROM categories WHERE name = '沪菜' LIMIT 1), '{"calories": 200, "protein": 10, "carbs": 25, "fat": 8}', 4.5, 2900, 87),
('小笼包', '上海小笼包', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=shanghai%20xiaolongbao%20steamed%20soup%20dumplings&image_size=square', (SELECT id FROM categories WHERE name = '沪菜' LIMIT 1), '{"calories": 180, "protein": 8, "carbs": 22, "fat": 7}', 4.6, 3200, 88),
('灌汤包', '开封灌汤包', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=kaifeng%20soup%20filled%20steamed%20buns&image_size=square', (SELECT id FROM categories WHERE name = '豫菜' LIMIT 1), '{"calories": 190, "protein": 9, "carbs": 24, "fat": 8}', 4.4, 2400, 83),
('锅贴', '香煎锅贴', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=pan%20fried%20dumplings%20golden%20crispy&image_size=square', (SELECT id FROM categories WHERE name = '鲁菜' LIMIT 1), '{"calories": 220, "protein": 12, "carbs": 28, "fat": 8}', 4.3, 2200, 82),
('韭菜盒子', '香脆韭菜盒子', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=chinese%20chive%20pocket%20pastry%20golden%20fried&image_size=square', (SELECT id FROM categories WHERE name = '鲁菜' LIMIT 1), '{"calories": 240, "protein": 8, "carbs": 32, "fat": 10}', 4.2, 1900, 80),

-- 外卖爆款汉堡薯条系列
('巨无霸汉堡', '经典巨无霸汉堡', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=big%20mac%20burger%20with%20double%20patties&image_size=square', (SELECT id FROM categories WHERE name = '西式快餐' LIMIT 1), '{"calories": 520, "protein": 25, "carbs": 45, "fat": 28}', 4.5, 3500, 90),
('芝士汉堡', '双层芝士汉堡', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=double%20cheese%20burger%20with%20melted%20cheese&image_size=square', (SELECT id FROM categories WHERE name = '西式快餐' LIMIT 1), '{"calories": 480, "protein": 22, "carbs": 40, "fat": 26}', 4.4, 3200, 88),
('鸡肉汉堡', '香脆鸡肉汉堡', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=crispy%20chicken%20burger%20with%20lettuce&image_size=square', (SELECT id FROM categories WHERE name = '西式快餐' LIMIT 1), '{"calories": 420, "protein": 20, "carbs": 38, "fat": 22}', 4.3, 2800, 86),
('鱼肉汉堡', '炸鱼汉堡', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=fish%20burger%20with%20tartar%20sauce&image_size=square', (SELECT id FROM categories WHERE name = '西式快餐' LIMIT 1), '{"calories": 380, "protein": 18, "carbs": 35, "fat": 20}', 4.2, 2400, 84),
('薯条', '金黄薯条', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=golden%20french%20fries%20crispy%20hot&image_size=square', (SELECT id FROM categories WHERE name = '西式快餐' LIMIT 1), '{"calories": 320, "protein": 4, "carbs": 42, "fat": 16}', 4.1, 2600, 85),
('鸡块', '麦乐鸡块', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=chicken%20nuggets%20golden%20crispy%20pieces&image_size=square', (SELECT id FROM categories WHERE name = '西式快餐' LIMIT 1), '{"calories": 280, "protein": 16, "carbs": 18, "fat": 18}', 4.3, 2800, 86),
('洋葱圈', '酥脆洋葱圈', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=crispy%20onion%20rings%20golden%20fried&image_size=square', (SELECT id FROM categories WHERE name = '西式快餐' LIMIT 1), '{"calories": 240, "protein": 4, "carbs": 28, "fat": 14}', 4.0, 2000, 82),

-- 奶茶果汁系列（外卖爆款）
('珍珠奶茶', '经典珍珠奶茶', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=classic%20bubble%20tea%20with%20tapioca%20pearls&image_size=square', (SELECT id FROM categories WHERE name = '饮品' LIMIT 1), '{"calories": 280, "protein": 4, "carbs": 58, "fat": 6}', 4.6, 3800, 92),
('芋泥奶茶', '香甜芋泥奶茶', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=taro%20milk%20tea%20purple%20creamy&image_size=square', (SELECT id FROM categories WHERE name = '饮品' LIMIT 1), '{"calories": 320, "protein": 5, "carbs": 62, "fat": 8}', 4.5, 3400, 89),
('红豆奶茶', '红豆奶茶', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=red%20bean%20milk%20tea%20with%20beans&image_size=square', (SELECT id FROM categories WHERE name = '饮品' LIMIT 1), '{"calories": 300, "protein": 6, "carbs": 56, "fat": 7}', 4.4, 3000, 87),
('椰果奶茶', '椰果奶茶', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=coconut%20jelly%20milk%20tea%20refreshing&image_size=square', (SELECT id FROM categories WHERE name = '饮品' LIMIT 1), '{"calories": 260, "protein": 3, "carbs": 54, "fat": 5}', 4.3, 2800, 86),
('布丁奶茶', '焦糖布丁奶茶', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=caramel%20pudding%20milk%20tea%20sweet&image_size=square', (SELECT id FROM categories WHERE name = '饮品' LIMIT 1), '{"calories": 340, "protein": 5, "carbs": 64, "fat": 9}', 4.4, 3200, 88),
('芒果汁', '鲜榨芒果汁', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=fresh%20mango%20juice%20tropical%20orange&image_size=square', (SELECT id FROM categories WHERE name = '饮品' LIMIT 1), '{"calories": 180, "protein": 1, "carbs": 44, "fat": 0}', 4.5, 2600, 85),
('西瓜汁', '清甜西瓜汁', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=fresh%20watermelon%20juice%20red%20refreshing&image_size=square', (SELECT id FROM categories WHERE name = '饮品' LIMIT 1), '{"calories": 120, "protein": 1, "carbs": 30, "fat": 0}', 4.3, 2200, 83),
('橙汁', '鲜榨橙汁', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=fresh%20orange%20juice%20vitamin%20c%20rich&image_size=square', (SELECT id FROM categories WHERE name = '饮品' LIMIT 1), '{"calories": 140, "protein": 2, "carbs": 34, "fat": 0}', 4.4, 2400, 84),
('苹果汁', '鲜榨苹果汁', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=fresh%20apple%20juice%20golden%20healthy&image_size=square', (SELECT id FROM categories WHERE name = '饮品' LIMIT 1), '{"calories": 130, "protein": 0, "carbs": 32, "fat": 0}', 4.2, 2000, 82),
('柠檬蜂蜜茶', '柠檬蜂蜜茶', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=lemon%20honey%20tea%20refreshing%20citrus&image_size=square', (SELECT id FROM categories WHERE name = '饮品' LIMIT 1), '{"calories": 100, "protein": 0, "carbs": 26, "fat": 0}', 4.3, 2200, 83),

-- 烧烤系列（夜宵爆款）
('烤羊肉串', '新疆烤羊肉串', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=xinjiang%20grilled%20lamb%20skewers%20spicy&image_size=square', (SELECT id FROM categories WHERE name = '烧烤' LIMIT 1), '{"calories": 180, "protein": 15, "carbs": 2, "fat": 12}', 4.7, 4200, 94),
('烤牛肉串', '香辣烤牛肉串', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=spicy%20grilled%20beef%20skewers%20charcoal&image_size=square', (SELECT id FROM categories WHERE name = '烧烤' LIMIT 1), '{"calories": 160, "protein": 14, "carbs": 1, "fat": 11}', 4.6, 3800, 92),
('烤鸡翅', '蜜汁烤鸡翅', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=honey%20glazed%20grilled%20chicken%20wings&image_size=square', (SELECT id FROM categories WHERE name = '烧烤' LIMIT 1), '{"calories": 200, "protein": 18, "carbs": 8, "fat": 12}', 4.8, 4500, 95),
('烤鸡腿', '香烤鸡腿', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=grilled%20chicken%20drumstick%20golden%20crispy&image_size=square', (SELECT id FROM categories WHERE name = '烧烤' LIMIT 1), '{"calories": 250, "protein": 22, "carbs": 5, "fat": 16}', 4.6, 3600, 90),
('烤茄子', '蒜蓉烤茄子', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=grilled%20eggplant%20with%20garlic%20sauce&image_size=square', (SELECT id FROM categories WHERE name = '烧烤' LIMIT 1), '{"calories": 120, "protein": 3, "carbs": 15, "fat": 6}', 4.4, 2800, 86),
('烤韭菜', '炭火烤韭菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=grilled%20chinese%20chives%20charcoal%20fire&image_size=square', (SELECT id FROM categories WHERE name = '烧烤' LIMIT 1), '{"calories": 80, "protein": 2, "carbs": 8, "fat": 4}', 4.2, 2200, 82),
('烤玉米', '黄油烤玉米', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=grilled%20corn%20with%20butter%20golden&image_size=square', (SELECT id FROM categories WHERE name = '烧烤' LIMIT 1), '{"calories": 150, "protein": 4, "carbs": 25, "fat": 5}', 4.3, 2600, 84),
('烤土豆', '孜然烤土豆', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=grilled%20potato%20with%20cumin%20spices&image_size=square', (SELECT id FROM categories WHERE name = '烧烤' LIMIT 1), '{"calories": 180, "protein": 4, "carbs": 35, "fat": 4}', 4.1, 2000, 81),
('烤鱿鱼', '铁板烤鱿鱼', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=grilled%20squid%20on%20iron%20plate&image_size=square', (SELECT id FROM categories WHERE name = '烧烤' LIMIT 1), '{"calories": 140, "protein": 18, "carbs": 3, "fat": 6}', 4.5, 3200, 88),
('烤生蚝', '蒜蓉烤生蚝', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=grilled%20oysters%20with%20garlic%20butter&image_size=square', (SELECT id FROM categories WHERE name = '烧烤' LIMIT 1), '{"calories": 100, "protein": 12, "carbs": 4, "fat": 4}', 4.6, 3400, 89),

-- 卤味系列（外卖爆款）
('卤鸭脖', '麻辣卤鸭脖', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=spicy%20braised%20duck%20neck%20red%20sauce&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 160, "protein": 12, "carbs": 3, "fat": 11}', 4.7, 4000, 93),
('卤鸭翅', '香辣卤鸭翅', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=spicy%20braised%20duck%20wings%20dark%20sauce&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 180, "protein": 14, "carbs": 2, "fat": 13}', 4.6, 3600, 91),
('卤鸭掌', '麻辣卤鸭掌', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=spicy%20braised%20duck%20feet%20collagen%20rich&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 120, "protein": 10, "carbs": 1, "fat": 8}', 4.5, 3200, 89),
('卤鸡爪', '香辣卤鸡爪', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=spicy%20braised%20chicken%20feet%20tender&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 140, "protein": 12, "carbs": 2, "fat": 9}', 4.6, 3400, 90),
('卤豆干', '五香卤豆干', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=five%20spice%20braised%20tofu%20squares&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 100, "protein": 8, "carbs": 6, "fat": 5}', 4.3, 2600, 85),
('卤蛋', '茶叶卤蛋', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=tea%20braised%20eggs%20marbled%20pattern&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 80, "protein": 6, "carbs": 1, "fat": 5}', 4.2, 2200, 83),
('卤藕片', '香辣卤藕片', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=spicy%20braised%20lotus%20root%20slices&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 60, "protein": 2, "carbs": 12, "fat": 1}', 4.1, 1800, 80),

-- 更多减脂餐
('藜麦沙拉', '彩虹藜麦沙拉', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=colorful%20quinoa%20salad%20with%20vegetables&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 180, "protein": 8, "carbs": 28, "fat": 5}', 4.5, 2800, 86),
('牛油果沙拉', '牛油果蔬菜沙拉', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=avocado%20vegetable%20salad%20healthy%20green&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 220, "protein": 6, "carbs": 12, "fat": 18}', 4.4, 2600, 85),
('三文鱼沙拉', '烟熏三文鱼沙拉', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=smoked%20salmon%20salad%20with%20greens&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 250, "protein": 20, "carbs": 8, "fat": 16}', 4.6, 3200, 88),
('金枪鱼沙拉', '金枪鱼蔬菜沙拉', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=tuna%20vegetable%20salad%20protein%20rich&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 200, "protein": 18, "carbs": 10, "fat": 10}', 4.5, 2900, 87),
('虾仁沙拉', '白灼虾仁沙拉', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=boiled%20shrimp%20salad%20fresh%20vegetables&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 160, "protein": 16, "carbs": 8, "fat": 6}', 4.4, 2700, 86),
('鸡胸肉沙拉', '香煎鸡胸肉沙拉', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=grilled%20chicken%20breast%20salad%20lean%20protein&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 240, "protein": 25, "carbs": 10, "fat": 12}', 4.5, 3000, 88),
('蔬菜汤', '清淡蔬菜汤', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=clear%20vegetable%20soup%20healthy%20light&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 80, "protein": 3, "carbs": 15, "fat": 1}', 4.2, 2000, 82),
('蒸蛋羹', '嫩滑蒸蛋羹', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=silky%20steamed%20egg%20custard%20smooth&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 120, "protein": 10, "carbs": 2, "fat": 8}', 4.3, 2200, 83),
('蒸蛋白', '纯蒸蛋白', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=steamed%20egg%20whites%20pure%20protein&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 60, "protein": 12, "carbs": 0, "fat": 0}', 4.1, 1800, 80),
('蒸鸡胸肉', '清蒸鸡胸肉', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=steamed%20chicken%20breast%20lean%20white%20meat&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 180, "protein": 32, "carbs": 0, "fat": 4}', 4.2, 2100, 82),

-- 地方特色小吃
('臭豆腐', '长沙臭豆腐', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=changsha%20stinky%20tofu%20fermented%20black&image_size=square', (SELECT id FROM categories WHERE name = '湘菜' LIMIT 1), '{"calories": 200, "protein": 12, "carbs": 15, "fat": 12}', 4.3, 2400, 84),
('螺蛳粉', '柳州螺蛳粉', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=liuzhou%20snail%20rice%20noodles%20spicy%20soup&image_size=square', (SELECT id FROM categories WHERE name = '桂菜' LIMIT 1), '{"calories": 350, "protein": 15, "carbs": 45, "fat": 12}', 4.6, 3600, 91),
('热干面', '武汉热干面', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=wuhan%20hot%20dry%20noodles%20sesame%20sauce&image_size=square', (SELECT id FROM categories WHERE name = '鄂菜' LIMIT 1), '{"calories": 380, "protein": 12, "carbs": 50, "fat": 16}', 4.5, 3200, 89),
('刀削面', '山西刀削面', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=shanxi%20knife%20cut%20noodles%20thick%20chewy&image_size=square', (SELECT id FROM categories WHERE name = '晋菜' LIMIT 1), '{"calories": 320, "protein": 10, "carbs": 55, "fat": 8}', 4.4, 2800, 86),
('兰州拉面', '兰州牛肉拉面', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=lanzhou%20beef%20noodles%20clear%20broth&image_size=square', (SELECT id FROM categories WHERE name = '西北菜' LIMIT 1), '{"calories": 400, "protein": 18, "carbs": 60, "fat": 10}', 4.7, 4000, 93),
('担担面', '四川担担面', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=sichuan%20dandan%20noodles%20spicy%20sesame&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 420, "protein": 14, "carbs": 55, "fat": 18}', 4.6, 3400, 90),
('重庆小面', '重庆小面', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=chongqing%20spicy%20noodles%20red%20oil&image_size=square', (SELECT id FROM categories WHERE name = '川菜' LIMIT 1), '{"calories": 380, "protein": 12, "carbs": 52, "fat": 15}', 4.5, 3000, 88),
('过桥米线', '云南过桥米线', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=yunnan%20crossing%20bridge%20rice%20noodles&image_size=square', (SELECT id FROM categories WHERE name = '滇菜' LIMIT 1), '{"calories": 300, "protein": 16, "carbs": 40, "fat": 8}', 4.4, 2600, 85),
('桂林米粉', '桂林米粉', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=guilin%20rice%20noodles%20clear%20soup&image_size=square', (SELECT id FROM categories WHERE name = '桂菜' LIMIT 1), '{"calories": 280, "protein": 12, "carbs": 45, "fat": 6}', 4.3, 2400, 83),
('沙县小吃', '沙县拌面', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=shaxian%20mixed%20noodles%20peanut%20sauce&image_size=square', (SELECT id FROM categories WHERE name = '闽菜' LIMIT 1), '{"calories": 320, "protein": 10, "carbs": 48, "fat": 12}', 4.2, 2200, 82),

-- 粥类和汤品
('白粥', '香滑白粥', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=smooth%20white%20rice%20porridge%20simple&image_size=square', (SELECT id FROM categories WHERE name = '粥品' LIMIT 1), '{"calories": 120, "protein": 2, "carbs": 28, "fat": 0}', 4.0, 1800, 80),
('小米粥', '养胃小米粥', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=nourishing%20millet%20porridge%20golden&image_size=square', (SELECT id FROM categories WHERE name = '粥品' LIMIT 1), '{"calories": 140, "protein": 4, "carbs": 30, "fat": 1}', 4.1, 2000, 81),
('瘦肉粥', '瘦肉白粥', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=lean%20pork%20rice%20porridge%20protein&image_size=square', (SELECT id FROM categories WHERE name = '粥品' LIMIT 1), '{"calories": 180, "protein": 12, "carbs": 25, "fat": 4}', 4.3, 2400, 84),
('青菜粥', '清淡青菜粥', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=light%20vegetable%20rice%20porridge%20green&image_size=square', (SELECT id FROM categories WHERE name = '粥品' LIMIT 1), '{"calories": 100, "protein": 3, "carbs": 22, "fat": 0}', 4.0, 1600, 79),
('鸡蛋粥', '鸡蛋花粥', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=egg%20flower%20rice%20porridge%20nutritious&image_size=square', (SELECT id FROM categories WHERE name = '粥品' LIMIT 1), '{"calories": 160, "protein": 8, "carbs": 26, "fat": 3}', 4.2, 2100, 82),
('海鲜粥', '鲜美海鲜粥', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=fresh%20seafood%20rice%20porridge%20delicious&image_size=square', (SELECT id FROM categories WHERE name = '粥品' LIMIT 1), '{"calories": 220, "protein": 16, "carbs": 28, "fat": 6}', 4.4, 2600, 85),

-- 更多减脂餐和轻食
('蒸蛋白配蔬菜', '蒸蛋白蔬菜拼盘', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=steamed%20egg%20whites%20with%20vegetables%20healthy&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 100, "protein": 14, "carbs": 8, "fat": 1}', 4.2, 2000, 82),
('水煮蛋', '水煮鸡蛋', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=boiled%20eggs%20simple%20protein&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 70, "protein": 6, "carbs": 0, "fat": 5}', 4.0, 1800, 80),
('蒸蛋', '水蒸蛋', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=steamed%20egg%20custard%20silky%20smooth&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 90, "protein": 8, "carbs": 1, "fat": 6}', 4.1, 1900, 81),
('蒸南瓜', '清蒸南瓜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=steamed%20pumpkin%20sweet%20orange&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 60, "protein": 2, "carbs": 14, "fat": 0}', 4.0, 1600, 79),
('蒸红薯', '蒸红薯', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=steamed%20sweet%20potato%20orange%20healthy&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 100, "protein": 2, "carbs": 24, "fat": 0}', 4.1, 1800, 80),
('蒸玉米', '蒸玉米', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=steamed%20corn%20yellow%20kernels&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 120, "protein": 4, "carbs": 26, "fat": 1}', 4.0, 1700, 79),
('蒸土豆', '蒸土豆', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=steamed%20potato%20fluffy%20white&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 110, "protein": 3, "carbs": 25, "fat": 0}', 3.9, 1600, 78),
('蒸胡萝卜', '蒸胡萝卜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=steamed%20carrots%20orange%20nutritious&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 50, "protein": 1, "carbs": 12, "fat": 0}', 3.8, 1400, 77),
('蒸西兰花', '蒸西兰花', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=steamed%20broccoli%20green%20healthy&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 40, "protein": 4, "carbs": 8, "fat": 0}', 4.0, 1500, 78),
('蒸菜花', '蒸菜花', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=steamed%20cauliflower%20white%20tender&image_size=square', (SELECT id FROM categories WHERE name = '健康轻食' LIMIT 1), '{"calories": 35, "protein": 3, "carbs": 7, "fat": 0}', 3.9, 1400, 77),

-- 更多夜宵和烧烤
('烤鱿鱼', '炭火烤鱿鱼', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=grilled%20squid%20charcoal%20fire%20night%20snack&image_size=square', (SELECT id FROM categories WHERE name = '烧烤' LIMIT 1), '{"calories": 180, "protein": 20, "carbs": 5, "fat": 8}', 4.4, 2800, 86),
('烤生蚝', '蒜蓉烤生蚝', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=grilled%20oysters%20garlic%20sauce%20seafood&image_size=square', (SELECT id FROM categories WHERE name = '烧烤' LIMIT 1), '{"calories": 120, "protein": 14, "carbs": 8, "fat": 4}', 4.6, 3200, 89),
('烤扇贝', '蒜蓉烤扇贝', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=grilled%20scallops%20garlic%20butter%20seafood&image_size=square', (SELECT id FROM categories WHERE name = '烧烤' LIMIT 1), '{"calories": 140, "protein": 16, "carbs": 6, "fat": 6}', 4.5, 3000, 88),
('烤韭菜', '烤韭菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=grilled%20chinese%20chives%20vegetable%20bbq&image_size=square', (SELECT id FROM categories WHERE name = '烧烤' LIMIT 1), '{"calories": 60, "protein": 3, "carbs": 8, "fat": 2}', 4.2, 2200, 83),
('烤金针菇', '烤金针菇', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=grilled%20enoki%20mushrooms%20bbq%20vegetable&image_size=square', (SELECT id FROM categories WHERE name = '烧烤' LIMIT 1), '{"calories": 50, "protein": 4, "carbs": 6, "fat": 1}', 4.1, 2000, 82),
('烤豆腐', '烤豆腐', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=grilled%20tofu%20golden%20crispy%20vegetarian&image_size=square', (SELECT id FROM categories WHERE name = '烧烤' LIMIT 1), '{"calories": 120, "protein": 12, "carbs": 4, "fat": 6}', 4.0, 1800, 81),
('烤玉米', '烤玉米', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=grilled%20corn%20charred%20sweet%20bbq&image_size=square', (SELECT id FROM categories WHERE name = '烧烤' LIMIT 1), '{"calories": 150, "protein": 5, "carbs": 32, "fat": 2}', 4.3, 2400, 84),
('烤红薯', '烤红薯', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=roasted%20sweet%20potato%20caramelized%20street%20food&image_size=square', (SELECT id FROM categories WHERE name = '烧烤' LIMIT 1), '{"calories": 180, "protein": 3, "carbs": 42, "fat": 0}', 4.2, 2100, 82),

-- 甜品和小食
('双皮奶', '顺德双皮奶', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=shunde%20double%20skin%20milk%20dessert%20smooth&image_size=square', (SELECT id FROM categories WHERE name = '甜品' LIMIT 1), '{"calories": 180, "protein": 6, "carbs": 20, "fat": 8}', 4.4, 2600, 85),
('龟苓膏', '龟苓膏', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=herbal%20jelly%20black%20traditional%20dessert&image_size=square', (SELECT id FROM categories WHERE name = '甜品' LIMIT 1), '{"calories": 80, "protein": 2, "carbs": 18, "fat": 0}', 4.1, 1900, 81),
('豆花', '嫩豆花', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=silky%20tofu%20pudding%20sweet%20dessert&image_size=square', (SELECT id FROM categories WHERE name = '甜品' LIMIT 1), '{"calories": 100, "protein": 8, "carbs": 12, "fat": 2}', 4.2, 2000, 82),
('红豆沙', '红豆沙', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=red%20bean%20paste%20sweet%20dessert%20soup&image_size=square', (SELECT id FROM categories WHERE name = '甜品' LIMIT 1), '{"calories": 160, "protein": 6, "carbs": 32, "fat": 1}', 4.0, 1800, 80),
('绿豆沙', '绿豆沙', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=mung%20bean%20paste%20cooling%20dessert%20soup&image_size=square', (SELECT id FROM categories WHERE name = '甜品' LIMIT 1), '{"calories": 140, "protein": 8, "carbs": 28, "fat": 1}', 4.1, 1900, 81),
('银耳莲子汤', '银耳莲子汤', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=white%20fungus%20lotus%20seed%20soup%20nourishing&image_size=square', (SELECT id FROM categories WHERE name = '甜品' LIMIT 1), '{"calories": 120, "protein": 4, "carbs": 26, "fat": 1}', 4.3, 2200, 83),

-- 国际美食
('意大利面', '番茄意大利面', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=tomato%20spaghetti%20italian%20pasta%20basil&image_size=square', (SELECT id FROM categories WHERE name = '西餐' LIMIT 1), '{"calories": 350, "protein": 12, "carbs": 60, "fat": 8}', 4.4, 2800, 86),
('披萨', '玛格丽特披萨', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=margherita%20pizza%20cheese%20tomato%20basil&image_size=square', (SELECT id FROM categories WHERE name = '西餐' LIMIT 1), '{"calories": 280, "protein": 14, "carbs": 35, "fat": 10}', 4.5, 3000, 88),
('牛排', '西冷牛排', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=sirloin%20steak%20grilled%20medium%20rare&image_size=square', (SELECT id FROM categories WHERE name = '西餐' LIMIT 1), '{"calories": 400, "protein": 35, "carbs": 0, "fat": 28}', 4.6, 3400, 90),
('三明治', '火腿三明治', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=ham%20sandwich%20lettuce%20tomato%20bread&image_size=square', (SELECT id FROM categories WHERE name = '西餐' LIMIT 1), '{"calories": 320, "protein": 18, "carbs": 35, "fat": 12}', 4.2, 2400, 84),
('沙拉', '凯撒沙拉', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=caesar%20salad%20lettuce%20croutons%20parmesan&image_size=square', (SELECT id FROM categories WHERE name = '西餐' LIMIT 1), '{"calories": 200, "protein": 8, "carbs": 12, "fat": 14}', 4.3, 2600, 85),

-- 日韩料理
('寿司', '三文鱼寿司', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=salmon%20sushi%20japanese%20rice%20fresh&image_size=square', (SELECT id FROM categories WHERE name = '日料' LIMIT 1), '{"calories": 180, "protein": 12, "carbs": 20, "fat": 6}', 4.5, 3000, 88),
('拉面', '日式拉面', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=japanese%20ramen%20rich%20broth%20noodles&image_size=square', (SELECT id FROM categories WHERE name = '日料' LIMIT 1), '{"calories": 450, "protein": 20, "carbs": 55, "fat": 18}', 4.4, 2800, 86),
('天妇罗', '虾天妇罗', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=shrimp%20tempura%20crispy%20batter%20japanese&image_size=square', (SELECT id FROM categories WHERE name = '日料' LIMIT 1), '{"calories": 220, "protein": 14, "carbs": 18, "fat": 12}', 4.3, 2400, 85),
('韩式烤肉', '韩式烤牛肉', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=korean%20bbq%20beef%20marinated%20grilled&image_size=square', (SELECT id FROM categories WHERE name = '韩料' LIMIT 1), '{"calories": 380, "protein": 28, "carbs": 8, "fat": 26}', 4.5, 3200, 89),
('泡菜', '韩式泡菜', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=korean%20kimchi%20fermented%20cabbage%20spicy&image_size=square', (SELECT id FROM categories WHERE name = '韩料' LIMIT 1), '{"calories": 40, "protein": 2, "carbs": 8, "fat": 0}', 4.2, 2000, 82),
('石锅拌饭', '韩式石锅拌饭', 'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=korean%20bibimbap%20stone%20bowl%20vegetables&image_size=square', (SELECT id FROM categories WHERE name = '韩料' LIMIT 1), '{"calories": 420, "protein": 16, "carbs": 65, "fat": 12}', 4.4, 2800, 86);